import { PrismaClient, ItemType, EquipSlot, WeaponCategory } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')
  // Run locally with `npm run db:seed` (uses DATABASE_URL)

  // Create initial rooms - 9-room grassy field area
  const rooms = [
    {
      roomId: '000',
      name: 'Room Zero',
      subtitle: '000',
      subtitlePosition: 'above',
      nameColor: 'white',
      subtitleColor: 'gray-500',
      icon: 'roomzero2',
      iconColor: 'gray-700',
      description: 'You are in an empty room. The walls are all gray and there are no windows or doors. The only light you see comes from a pillar in the center of the room. There is a small sign on the side of the pillar and a small piece of paper on the floor.',
      dangerLevel: 0,
      isSafe: true,
      north: null,
      south: null,
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false
    },
    {
      roomId: '001',
      name: 'Grassy Field Crossroads',
      subtitle: 'This is it. The world is yours.',
      subtitlePosition: 'above',
      nameColor: 'grass',
      subtitleColor: 'blue-400',
      icon: 'sun',
      iconColor: 'yellow-400',
      description: 'You find yourself standing in the middle of a large, grassy field. The air is warm, and the sky above is bright blue. A sign stands nearby with a golden chest at its base. To the southwest, you see a small, cozy cabin.',
      dangerLevel: 0,
      isSafe: true,
      north: '005',
      south: '002',
      east: '006',
      west: '004',
      up: null,
      down: null,
      northeast: '021',
      northwest: '020',
      southeast: '007',
      southwest: '003',
      hasFire: false,
      hasCraftingTable: false
    },
    {
      roomId: '002',
      name: 'Grassy Field South',
      subtitle: 'Redberry Patch',
      subtitlePosition: 'below',
      nameColor: 'grass',
      subtitleColor: 'red-500',
      icon: 'redberry',
      iconColor: 'red-500',
      description: 'The grass starts to get rocky in this area. A redberry bush is here, and consuming its fruit will restore lost health points. An entrance to a cave can be seen to the east, and a cabin is visible to the west.',
      dangerLevel: 0,
      isSafe: true,
      north: '001',
      south: null,
      east: '007',
      west: '003',
      up: null,
      down: null,
      northeast: '006',
      northwest: '004',
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false
    },
    {
      roomId: '003',
      name: 'Old Man',
      subtitle: 'Wood Cabin',
      subtitlePosition: 'below',
      nameColor: 'neutral-200',
      subtitleColor: 'dirt',
      icon: 'cabin2',
      iconColor: 'dirt',
      description: 'The cabin is warm and cozy. A cooking fire burns here, and the Old Man is rocking in his chair. He insists that you make yourself at home and stay as long as you like, and encourages you to start and complete your first quests here.',
      dangerLevel: 0,
      isSafe: true,
      north: '004',
      south: null,
      east: '002',
      west: '003c',
      up: null,
      down: '003b',
      northeast: '001',
      northwest: null,
      southeast: null,
      southwest: '013',
      hasFire: true,
      hasCraftingTable: true,
      directionColors: { down: 'dirt' }
    },
    {
      roomId: '003b',
      name: 'Cabin Basement',
      subtitle: 'Underground',
      subtitlePosition: 'below',
      nameColor: 'neutral-400',
      subtitleColor: 'gray-500',
      icon: 'basement',
      iconColor: 'gray-600',
      description: 'The basement is waterlogged and dirty, with a putrid smell that permeates the air. There are rats here that can be attacked. To return to the cabin above, simply go back up the stairs.',
      dangerLevel: 1,
      isSafe: false,
      north: null,
      south: null,
      east: null,
      west: '003bb',
      up: '003',
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      hasSearch: true,
      directionColors: { west: 'dirt' }
    },
    {
      roomId: '003bb',
      name: 'Destroyed Basement',
      subtitle: 'Underground',
      subtitlePosition: 'below',
      nameColor: 'neutral-400',
      subtitleColor: 'gray-500',
      icon: 'basement2',
      iconColor: 'gray-600',
      description: 'The basement is completely destroyed and waterlogged. There is rat waste everywhere. In between battles, you can rest to regain lost hit points or search the rubble for anything that may be useful.',
      dangerLevel: 2,
      isSafe: false,
      north: null,
      south: null,
      east: '003b',
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      hasSearch: true,
      directionColors: { east: 'dirt' }
    },
    {
      roomId: '003c',
      name: 'Young Soldier',
      subtitle: 'Weapons Training',
      subtitlePosition: 'below',
      nameColor: 'blue-400',
      subtitleColor: 'gray-200',
      icon: 'trainingarea',
      iconColor: 'blue-400',
      description: 'The training grounds are located on a cliff overlooking the ocean. Racks of weapons and armor stand ready for use, and a young soldier is here to guide you through your training. The breeze carries the fresh, salty sea air throughout the area.',
      dangerLevel: 0,
      isSafe: true,
      north: null,
      south: null,
      east: '003',
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false
    },
    {
      roomId: '004',
      name: 'Grassy Field West',
      subtitle: 'Flower Patch',
      subtitlePosition: 'below',
      nameColor: 'grass',
      subtitleColor: 'yellow-400',
      icon: 'flower',
      iconColor: 'yellow-400',
      description: 'A bright flower patch grows here. You see a cabin to the south and a beach to the west.',
      dangerLevel: 0,
      isSafe: true,
      north: '020',
      south: '003',
      east: '001',
      west: '014',
      up: null,
      down: null,
      northeast: '005',
      northwest: null,
      southeast: '002',
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { west: 'dirt' }
    },
    {
      roomId: '013',
      name: 'Marsh Behind the Cabin',
      subtitle: 'Gator Territory',
      subtitlePosition: 'below',
      nameColor: 'neutral-200',
      subtitleColor: 'green-600',
      icon: 'gator',
      iconColor: 'green-700',
      description: 'A gross swampy marsh. You see some gator tracks in the mud.',
      dangerLevel: 5,
      isSafe: false,
      north: null,
      south: null,
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: '003',
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: {}
    },
    {
      roomId: '014',
      name: 'Dirt Road West',
      subtitle: 'Path to the beach',
      subtitlePosition: 'below',
      nameColor: 'dirt',
      subtitleColor: 'sand',
      icon: 'sign2',
      iconColor: 'dirt',
      description: 'You are on a dirt path heading down to the beach.',
      dangerLevel: 0,
      isSafe: true,
      north: null,
      south: null,
      east: '004',
      west: '017',
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { west: 'sand' }
    },
    {
      roomId: '017',
      name: 'On the Beach',
      subtitle: 'Rats spotted nearby',
      subtitlePosition: 'below',
      nameColor: 'blue-300',
      subtitleColor: 'sand',
      icon: 'beach-umbrella',
      iconColor: 'sand',
      description: 'The Sun is directly overhead and there is a cool breeze. The waves slowly roll in. You notice some scraggly rats scurrying along the sand.',
      dangerLevel: 1,
      isSafe: false,
      north: '016',
      south: '018',
      east: '014',
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'sand', south: 'sand',east: 'dirt'},
    },
    {
      roomId: '018',
      name: 'Rocky Beach',
      subtitle: '',
      subtitlePosition: 'below',
      nameColor: 'blue-300',
      subtitleColor: 'sand',
      icon: 'beach-crab',
      iconColor: 'sand',
      description: 'The beach becomes rocky here. Jagged stones jut up from the sand and the waves crash harder against them.',
      dangerLevel: 2,
      isSafe: false,
      north: '017',
      south: '019',
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'sand', south: 'sand' },
    },
    {
      roomId: '019',
      name: 'Sand Crab Nest',
      subtitle: '',
      subtitlePosition: 'below',
      nameColor: 'blue-300',
      subtitleColor: 'sand',
      icon: 'beach-crabs',
      iconColor: 'sand',
      description: 'This part of the beach is swarming with Sand Crabs. They just won\'t stop! Teleport to the Grassy Field to escape here.',
      dangerLevel: 3,
      isSafe: false,
      north: '018',
      south: null,
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'sand' },
    },
    {
      roomId: '016',
      name: 'Abandoned Docks',
      subtitle: 'Giant Rats are here!',
      subtitlePosition: 'below',
      nameColor: 'blue-400',
      subtitleColor: 'red-400',
      icon: 'beach-dock',
      iconColor: 'sand',
      description: 'You stand on a worn wooden dock. A vast blue ocean is to your west. Giant rats have taken over the docks and they are not happy to see you.',
      dangerLevel: 2,
      isSafe: false,
      north: '015',
      south: '017',
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'sand', south: 'sand'}
    },
    {
      roomId: '015',
      name: 'On the Beach',
      subtitle: 'by a Giant Rock',
      subtitlePosition: 'below',
      nameColor: 'blue-300',
      subtitleColor: 'gray-300',
      icon: 'beach-rock',
      iconColor: 'sand',
      description: 'The Sun is directly overhead and there is a cool breeze. You can mine stone from the giant rocks here. Large sand crabs cling to the rocks — they look passive, but do not be fooled.',
      dangerLevel: 1,
      isSafe: false,
      north: null,
      south: '016',
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: {south: 'sand'},
    },
    {
      roomId: '005',
      name: 'Grassy Field North',
      subtitle: 'Blueberry patch',
      subtitlePosition: 'below',
      nameColor: 'grass',
      subtitleColor: 'blue-500',
      icon: 'blueberry',
      iconColor: 'blue-500',
      description: 'Blueberry bushes grow in this part of the field. To the west you see a waterfall and to the east an odd tent. To the south you see the main crossroads.',
      dangerLevel: 0,
      isSafe: true,
      north: null,
      south: '001',
      east: '021',
      west: '020',
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: '006',
      southwest: '004',
      hasFire: false,
      hasCraftingTable: false
    },
    {
      roomId: '006',
      name: 'Grassy Field East',
      subtitle: 'Basic Shop',
      subtitlePosition: 'below',
      nameColor: 'grass',
      subtitleColor: 'dirt',
      icon: 'shop',
      iconColor: 'dirt',
      description: 'A Basic Shop is set up here where you can buy and sell items. To the south is a cave and north is a strange tent. To the far east you see a forest.',
      dangerLevel: 0,
      isSafe: true,
      north: '021',
      south: '007',
      east: null,
      west: '001',
      up: null,
      down: null,
      northeast: null,
      northwest: '005',
      southeast: null,
      southwest: '002',
      hasFire: false,
      hasCraftingTable: false
    },
    {
      roomId: '007',
      name: 'Young Soldier',
      subtitle: 'Weapons Training',
      subtitlePosition: 'below',
      nameColor: 'grass',
      subtitleColor: 'gray-600',
      icon: 'cave1',
      iconColor: 'gray-600',
      description: 'Robert, a brave soldier, has set up a training area in the Grassy Field. Some weapons and dummies are arranged for practice. A dark cave can be seen to the south. There is a sign here.',
      dangerLevel: 0,
      isSafe: false,
      north: '006',
      south: '008',
      east: null,
      west: '002',
      up: null,
      down: null,
      northeast: null,
      northwest: '001',
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { south: 'gray-600' }
    },
    {
      roomId: '008',
      name: 'Spider Cave',
      subtitle: 'Exit',
      subtitlePosition: 'above',
      nameColor: 'gray-300',
      subtitleColor: 'gray-500',
      icon: 'spider1',
      iconColor: 'gray-500',
      description: 'A cramped tunnel connects the cave to the grassy field above. Webs cling to the rocky walls near the entrance, and the air grows stale and cool as you move deeper in.',
      dangerLevel: 2,
      isSafe: false,
      north: '007',
      south: '009',
      east: '011',
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'grass', south: 'gray-600', east: 'gray-600' }
    },
    {
      roomId: '009',
      name: 'Spider Cave',
      subtitle: '#009',
      subtitlePosition: 'below',
      nameColor: 'gray-300',
      subtitleColor: 'gray-600',
      icon: 'scorpion1',
      iconColor: 'gray-500',
      description: 'A wide cavern with thick webs stretched between stone pillars. Something rustles in the darkness above.',
      dangerLevel: 3,
      isSafe: false,
      north: '008',
      south: null,
      east: '010',
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'gray-600', east: 'gray-600' }
    },
    {
      roomId: '010',
      name: 'Spider Cave',
      subtitle: '#010',
      subtitlePosition: 'below',
      nameColor: 'gray-300',
      subtitleColor: 'gray-600',
      icon: 'spider1',
      iconColor: 'gray-500',
      description: 'Deeper in the cave, the webs grow denser and the air thicker. Faint phosphorescent fungus clings to the walls, casting a pale glow on the silken tunnels ahead.',
      dangerLevel: 4,
      isSafe: false,
      north: '011',
      south: null,
      east: null,
      west: '009',
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'gray-600', west: 'gray-600' }
    },
    {
      roomId: '011',
      name: 'Spider Cave',
      subtitle: '#011',
      subtitlePosition: 'below',
      nameColor: 'gray-300',
      subtitleColor: 'gray-600',
      icon: 'spider2',
      iconColor: 'gray-500',
      description: 'A junction chamber where multiple web-lined tunnels converge. The ceiling drips with moisture. Movement overhead suggests you are not alone.',
      dangerLevel: 3,
      isSafe: false,
      north: null,
      south: '010',
      east: '012',
      west: '008',
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { south: 'gray-600', east: 'gray-600', west: 'gray-600' }
    },
    {
      roomId: '012',
      name: 'Above the',
      subtitle: 'Scorpion Pit',
      subtitlePosition: 'below',
      nameColor: 'white',
      subtitleColor: 'red-800',
      icon: 'scorpion2',
      iconColor: 'red-800',
      description: 'A narrow ledge overlooks a deep pit far below. The smell of venom and decay drifts upward. A rusted iron grate covers a passage that descends into the scorpion pit below.',
      dangerLevel: 5,
      isSafe: false,
      north: null,
      south: null,
      east: null,
      west: '011',
      up: null,
      down: '012b',
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { west: 'gray-600', down: 'red-900' }
    },
    {
      roomId: '012b',
      name: 'Scorpion Pit',
      subtitle: 'EXIT',
      subtitlePosition: 'below',
      nameColor: 'red-900',
      subtitleColor: 'yellow-300',
      icon: 'scorpion3',
      iconColor: 'red-900',
      description: 'The pit floor writhes with scorpions. The walls are slick with venom and the air is thick and suffocating. A ledge high above marks the only way back out. A narrow passage leads deeper into the darkness.',
      dangerLevel: 5,
      isSafe: false,
      north: null,
      south: '012c',
      east: null,
      west: null,
      up: '012',
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { up: 'gray-600', south: 'red-900' }
    },
    {
      roomId: '012c',
      name: 'Scorpion Pit',
      subtitle: 'Path',
      subtitlePosition: 'below',
      nameColor: 'red-900',
      subtitleColor: 'gray-500',
      icon: 'scorpion4',
      iconColor: 'red-900',
      description: 'A narrow winding passage carved through the rock. The walls glisten with dried venom. The air grows thicker as the passage winds deeper into the scorpion dungeon.',
      dangerLevel: 6,
      isSafe: false,
      north: '012b',
      south: null,
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: '012e',
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'red-900', northwest: 'red-900' }
    },
    {
      roomId: '012d',
      name: 'Scorpion',
      subtitle: 'Control Room',
      subtitlePosition: 'below',
      nameColor: 'white',
      subtitleColor: 'green-400',
      icon: 'rat2',
      iconColor: 'gray-500',
      description: 'An ancient carved chamber with strange symbols etched into the walls. A massive stone mechanism dominates the center, its purpose long forgotten. Something small and furtive scurries in the shadows.',
      dangerLevel: 5,
      isSafe: false,
      north: '012e',
      south: null,
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'red-900' }
    },
    {
      roomId: '012e',
      name: 'Scorpion',
      subtitle: 'Guard Room',
      subtitlePosition: 'below',
      nameColor: 'white',
      subtitleColor: 'blue-400',
      icon: 'scorpion5',
      iconColor: 'red-900',
      iconSize: 'md',
      description: 'A wide antechamber flanked by stone pillars worn smooth by centuries of passage. Scorpion husks litter the floor. Whatever guards this place is always watching.',
      dangerLevel: 7,
      isSafe: false,
      north: '012f',
      south: '012d',
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: '012c',
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'red-900', south: 'red-900', southeast: 'red-900' }
    },
    {
      roomId: '012f',
      name: 'Scorpion',
      subtitle: 'Hall',
      subtitlePosition: 'below',
      nameColor: 'white',
      subtitleColor: 'yellow-400',
      icon: 'scorpion6',
      iconColor: 'red-900',
      iconSize: 'md',
      description: 'A long vaulted hall stretching deeper into the earth. Torchless sconces line the walls, long cold. The air is heavy with the musk of chitinous creatures and the faint clicking of claws on stone.',
      dangerLevel: 10,
      isSafe: false,
      north: null,
      south: '012e',
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: '012g',
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { south: 'red-900', northeast: 'red-900' }
    },
    {
      roomId: '012g',
      name: 'Scorpion Queen',
      subtitle: 'Nest',
      subtitlePosition: 'below',
      nameColor: 'white',
      subtitleColor: 'green-500',
      icon: 'scorpion7',
      iconColor: 'red-900',
      iconSize: 'lg',
      description: 'A vast circular chamber dominated by a writhing mass of scorpion eggs and shed exoskeletons. The walls pulse with bioluminescent fungus. Something massive stirs at the center.',
      dangerLevel: 15,
      isSafe: false,
      north: '012h',
      south: null,
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: '012f',
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { north: 'red-900', southwest: 'red-900' }
    },
    {
      roomId: '012h',
      name: 'Scorpion',
      subtitle: 'Throne Room',
      subtitlePosition: 'below',
      nameColor: 'white',
      subtitleColor: 'red-900',
      icon: 'scorpion8',
      iconColor: 'red-800',
      iconSize: 'xl',
      description: 'The deepest chamber of the scorpion dungeon. Bones of past challengers line the walls. A massive obsidian throne commands the room, and upon it coils the most lethal creature in the cave.',
      dangerLevel: 30,
      isSafe: false,
      north: null,
      south: '012g',
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { south: 'red-900' }
    },
    {
      roomId: '020',
      name: 'Healing Springs',
      subtitle: 'Mountain Waterfall',
      subtitlePosition: 'below',
      nameColor: 'grass',
      subtitleColor: 'blue-400',
      icon: 'waterfall',
      iconColor: 'blue-400',
      description: 'You discover a beautiful waterfall cascading into a crystal-clear pool. The water glows with a soft blue light, and you feel rejuvenated just being near it.',
      dangerLevel: 0,
      isSafe: true,
      north: null,
      south: '004',
      east: '005',
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: '000',
      southeast: '001',
      southwest: null,
      hasFire: false,
      hasCraftingTable: false,
      directionColors: { northwest: 'blue-400'}
    },
    {
      roomId: '021',
      name: 'Pajama Shaman',
      subtitle: 'Shop & Skills',
      subtitlePosition: 'below',
      nameColor: 'purple-400',
      subtitleColor: 'gray-100',
      icon: 'tent',
      iconColor: 'purple-400',
      description: 'A hooded man has set up a strange tent here with a makeshift shop. He is selling some basic items and also teaching some important skills.',
      dangerLevel: 0,
      isSafe: true,
      north: null,
      south: '006',
      east: null,
      west: '005',
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: '001',
      hasFire: false,
      hasCraftingTable: false
    },
    {
      roomId: '999',
      name: 'The Lobby',
      subtitle: '',
      subtitlePosition: 'above',
      nameColor: 'gray-100',
      subtitleColor: 'blue-300',
      icon: 'environment-lobby',
      iconColor: 'gray-400',
      description: 'You find yourself in the center of a floating platform high in the sky bathed in sunlight. You are surrounded by a massive ring of pillars. The ground is a smooth, polished surface of white marble.',
      dangerLevel: 0,
      isSafe: true,
      north: null,
      south: null,
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false
    },
    {
      roomId: '088',
      name: 'Solar Office',
      subtitle: 'Central Operations',
      subtitlePosition: 'below',
      nameColor: 'gray-100',
      subtitleColor: 'gray-400',
      icon: 'solaroffice',
      iconColor: 'blue-300',
      description: 'A wide, open-plan command office with dark composite walls and a polished floor, housing a range of personalized workstations. Transparent displays float above each desk, presenting system data and tactical readouts. One full wall is a reinforced viewport looking out onto a nearby star, its light filtered through polarized panels that serve as the primary illumination for the space.',
      dangerLevel: 0,
      isSafe: true,
      north: null,
      south: null,
      east: null,
      west: null,
      up: null,
      down: null,
      northeast: null,
      northwest: null,
      southeast: null,
      southwest: null,
      hasFire: false,
      hasCraftingTable: false
    }
  ]

  // Create rooms
  for (const roomData of rooms) {
    await prisma.room.upsert({
      where: { roomId: roomData.roomId },
      update: roomData,
      create: roomData
    })
  }

  // Seed item templates (idempotent by slug)
  const itemTemplates = [
    {
      id: 'flower_001',
      slug: 'flower',
      name: 'Flower',
      description: 'A beautiful wildflower from the flower patch.',
      type: ItemType.MISC,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10,
    },
    {
      id: 'redberry_001',
      slug: 'redberry',
      name: 'Redberry',
      description: 'A juicy redberry that restores health.',
      type: ItemType.CONSUMABLE,
      maxStack: 99999,
      maxPerPlayer: null,
      value: 10,
    },
    {
      id: 'blueberry_001',
      slug: 'blueberry',
      name: 'Blueberry',
      description: 'A juicy blueberry that restores mana.',
      type: ItemType.CONSUMABLE,
      maxStack: 99999,
      maxPerPlayer: null,
      value: 10,
    },
    {
      id: 'welcome-book',
      slug: 'welcome-book',
      name: 'Welcome Book',
      description: 'A leather-bound book welcoming adventurers to the world.',
      type: ItemType.MISC,
      maxStack: 99999,
      maxPerPlayer: null,
      value: 10,
      canSell: true,
      canDrop: false,
    },
    {
      id: 'shovel_001',
      slug: 'shovel',
      name: 'Shovel',
      description: 'A sturdy shovel for digging.',
      type: ItemType.MISC,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10,
    },
    {
      id: 'dagger_001',
      slug: 'dagger',
      name: 'Dagger',
      description: 'A sharp, lightweight dagger perfect for quick strikes.',
      type: ItemType.EQUIPMENT,
      maxStack: 1000,
      maxPerPlayer: 1000,
      value: 50,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 1 } },
    },
    {
      id: 'short-sword_001',
      slug: 'short-sword',
      name: 'Short Sword',
      description: 'A short, practical sword for close combat.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 50,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { icon: 'equipment-shortsword', statMods: { str: 4 } },
    },
    {
      id: 'red-potion_001',
      slug: 'red-potion',
      name: 'Red Potion',
      description: 'A red potion that restores health when consumed.',
      type: ItemType.CONSUMABLE,
      maxStack: 99,
      maxPerPlayer: null,
      value: 100,
    },
    {
      id: 'blue-potion_001',
      slug: 'blue-potion',
      name: 'Blue Potion',
      description: 'A blue potion that restores mana when consumed.',
      type: ItemType.CONSUMABLE,
      maxStack: 99,
      maxPerPlayer: null,
      value: 100,
    },
    {
      id: 'dirt_001',
      slug: 'dirt',
      name: 'Dirt',
      description: 'A handful of common dirt, useful for crafting and building.',
      type: ItemType.MISC,
      maxStack: 99999,
      maxPerPlayer: null,
      value: 10,
    },
    {
      id: 'sand_001',
      slug: 'sand',
      name: 'Sand',
      description: 'Fine grains of sand, collected from the beach.',
      type: ItemType.MISC,
      maxStack: 99999,
      maxPerPlayer: null,
      value: 10,
    },
    {
      id: 'stone_001',
      slug: 'stone',
      name: 'Stone',
      description: 'A solid piece of stone, useful for construction and crafting.',
      type: ItemType.MISC,
      maxStack: 99999,
      maxPerPlayer: null,
      value: 10,
    },
    {
      id: 'wood_001',
      slug: 'wood',
      name: 'Wood',
      description: 'A piece of wood, harvested from trees.',
      type: ItemType.MISC,
      maxStack: 99999,
      maxPerPlayer: null,
      value: 10,
    },
    {
      id: 'hatchet_001',
      slug: 'hatchet',
      name: 'Hatchet',
      description: 'A small axe used for chopping wood.',
      type: ItemType.MISC,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10,
    },
    {
      id: 'pickaxe_001',
      slug: 'pickaxe',
      name: 'Pickaxe',
      description: 'A sturdy pickaxe for mining stone and ore.',
      type: ItemType.MISC,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10,
    },
    {
      id: 'mace_001',
      slug: 'mace',
      name: 'Mace',
      description: 'A heavy mace with a solid metal head, perfect for crushing armor.',
      type: ItemType.EQUIPMENT,
      maxStack: 1000,
      maxPerPlayer: 1000,
      value: 400,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 4, mag: 2 } },
    },
    {
      id: 'bo_001',
      slug: 'bo',
      name: 'Bo',
      description: 'A long wooden staff that requires both hands to wield effectively.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 400,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 7 } },
    },
    {
      id: 'basic-shield_001',
      slug: 'basic-shield',
      name: 'Basic Shield',
      description: 'A simple wooden shield that provides basic protection.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 100,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { def: 7 } },
    },
    {
      id: 'blue-hood_001',
      slug: 'blue-hood',
      name: 'Blue Hood',
      description: 'A comfortable blue hood that covers the head.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10,
      equipSlot: EquipSlot.HEAD,
      metadata: { statMods: { mag: 2 } },
    },
    {
      id: 'padded-armor_001',
      slug: 'padded-armor',
      name: 'Padded Armor',
      description: 'Lightweight padded armor that provides basic protection without hindering movement.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10,
      equipSlot: EquipSlot.BODY,
      metadata: { statMods: { def: 13 } },
    },
    {
      id: 'black-gloves_001',
      slug: 'black-gloves',
      name: 'Black Gloves',
      description: 'Stylish black gloves that provide a good grip.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10,
      equipSlot: EquipSlot.HANDS,
      metadata: { statMods: { str: 1, def: 2 } },
    },
    {
      id: 'black-boots_001',
      slug: 'black-boots',
      name: 'Black Boots',
      description: 'Sturdy black boots that protect the feet and provide good traction.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10,
      equipSlot: EquipSlot.FEET,
      metadata: { statMods: { str: 1, mag: -5 } },
    },
    {
      id: 'master-sword_001',
      slug: 'master-sword',
      name: 'Master Sword',
      description: 'A legendary blade of immense power, forged with ancient magic. Its gleaming edge cuts through any foe.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 200, def: 100 } },
    },
    {
      id: 'crossbow-bolt_001',
      slug: 'crossbow-bolt',
      name: 'Crossbow Bolt',
      description: 'A short, heavy bolt for use with a crossbow.',
      type: ItemType.MISC,
      maxStack: 100,
      value: 2,
    },
    {
      id: 'cooked-meat_001',
      slug: 'cooked-meat',
      name: 'Cooked Meat',
      description: 'A piece of cooked meat that restores health when consumed.',
      type: ItemType.CONSUMABLE,
      maxStack: 10,
      value: 5,
    },
    {
      id: 'arrow_001',
      slug: 'arrow',
      name: 'Arrow',
      description: 'A wooden arrow with a steel tip, used with a bow.',
      type: ItemType.MISC,
      maxStack: 100,
      value: 1,
    },
    {
      id: 'long-sword_001',
      slug: 'long-sword',
      name: 'Long Sword',
      description: 'A sturdy long sword with good reach and solid damage.',
      type: ItemType.EQUIPMENT,
      maxStack: 1000,
      maxPerPlayer: 1000,
      value: 400,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 5 } },
    },
    {
      id: 'training-sword_001',
      slug: 'training-sword',
      name: 'Training Sword',
      description: 'A blunt practice sword used to learn the basics of swordsmanship.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 50,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 3 } },
    },
    {
      id: 'broad-sword_001',
      slug: 'broad-sword',
      name: 'Broad Sword',
      description: 'A wide-bladed sword that deals solid damage and deflects incoming blows.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 400,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 4, def: 2 } },
    },
    {
      id: 'club_001',
      slug: 'club',
      name: 'Club',
      description: 'A crude wooden club. Heavy and slow, but hits hard.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 400,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 6, def: -2 } },
    },
    {
      id: 'flail_001',
      slug: 'flail',
      name: 'Flail',
      description: 'A spiked iron ball on a chain. Difficult to block and hard to defend against.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 1200,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 7, def: 6 } },
    },
    {
      id: 'morning-star_001',
      slug: 'morning-star',
      name: 'Morning Star',
      description: 'A mace topped with a spiked metal head, infused with dark energy.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 1200,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 6, mag: 4 } },
    },
    {
      id: 'samurai-sword_001',
      slug: 'samurai-sword',
      name: 'Samurai Sword',
      description: 'A finely curved blade forged with eastern techniques. Razor sharp and perfectly balanced.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 1200,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 8 } },
    },
    {
      id: 'gladius_001',
      slug: 'gladius',
      name: 'Gladius',
      description: 'A short, double-edged sword favored by arena warriors. Powerful and versatile.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 3000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 9, def: 2, mag: 2 } },
    },
    {
      id: 'basic-staff_001',
      slug: 'basic-staff',
      name: 'Basic Staff',
      description: 'A simple wooden staff that channels magical energy.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 200,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { mag: 3 } },
    },
    {
      id: 'wooden-staff_001',
      slug: 'wooden-staff',
      name: 'Wooden Staff',
      description: 'A sturdy wooden staff reinforced with arcane carvings.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 400,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 1, mag: 5 } },
    },
    {
      id: 'wand_001',
      slug: 'wand',
      name: 'Wand',
      description: 'A slender wand that amplifies magic at the cost of physical prowess.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 800,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: -2, mag: 9 } },
    },
    {
      id: 'wizard-staff_001',
      slug: 'wizard-staff',
      name: 'Wizard Staff',
      description: 'A powerful staff humming with arcane power, favored by master spellcasters.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { mag: 8 } },
    },
    {
      id: 'demon-dagger_001',
      slug: 'demon-dagger',
      name: 'Demon Dagger',
      description: 'A sinister blade etched with demonic runes. Deals physical and magical damage.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 5, mag: 10 } },
    },
    {
      id: 'gray-wand_001',
      slug: 'gray-wand',
      name: 'Gray Wand',
      description: 'An ancient wand of immense magical power. Dangerous to wield — drains body and will.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: -5, def: -5, mag: 15 } },
    },
    {
      id: 'leather-whip_001',
      slug: 'leather-whip',
      name: 'Leather Whip',
      description: 'A long braided whip that strikes with surprising force.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 8000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 14 } },
    },
    {
      id: 'three-chained-flail_001',
      slug: 'three-chained-flail',
      name: 'Three-Chained Flail',
      description: 'Three spiked balls spinning on chains. Devastating and nearly impossible to block.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 15, mag: 5 } },
    },
    {
      id: 'bastard-sword_001',
      slug: 'bastard-sword',
      name: 'Bastard Sword',
      description: 'A versatile longsword that can be wielded one or two-handed.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 11 } },
    },
    {
      id: 'giant-club_001',
      slug: 'giant-club',
      name: 'Giant Club',
      description: 'A massive club torn from a tree trunk. Crushes enemies but disrupts your focus.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 5000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 13, mag: -3 } },
    },
    {
      id: 'great-white-sword_001',
      slug: 'great-white-sword',
      name: 'Great White Sword',
      description: 'A legendary white blade radiating holy power. Few have the strength to wield it.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 50000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { statMods: { str: 17, def: 7, mag: 7 } },
    },
    {
      id: 'training-2h-sword_001',
      slug: 'training-2h-sword',
      name: 'Training 2H Sword',
      description: 'A heavy blunt blade used to learn two-handed sword techniques.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 100,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 6 } },
    },
    {
      id: 'battle-axe_001',
      slug: 'battle-axe',
      name: 'Battle Axe',
      description: 'A massive two-handed axe that cleaves through enemies at the cost of defense.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 800,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 11, def: -2 } },
    },
    {
      id: 'warhammer_001',
      slug: 'warhammer',
      name: 'Warhammer',
      description: 'An enormous hammer built to shatter armor. Leaves you open to magic.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 900,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 13, mag: -5 } },
    },
    {
      id: 'wooden-bo_001',
      slug: 'wooden-bo',
      name: 'Wooden Bo',
      description: 'A hardwood bo staff reinforced with arcane runes.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 1000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 9, mag: 3 } },
    },
    {
      id: 'pike_001',
      slug: 'pike',
      name: 'Pike',
      description: 'A long spear-like weapon with exceptional reach and defensive capability.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 2500,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 11, def: 11 } },
    },
    {
      id: 'claymore_001',
      slug: 'claymore',
      name: 'Claymore',
      description: 'A great two-handed sword of Scottish design, powerful in all respects.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 5000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 13, mag: 2, def: 2 } },
    },
    {
      id: 'great-sword_001',
      slug: 'great-sword',
      name: 'Great Sword',
      description: 'A massive two-handed blade of immense cutting power.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 17 } },
    },
    {
      id: 'bo-staff_001',
      slug: 'bo-staff',
      name: 'Bo Staff',
      description: 'A balanced staff that channels both physical and magical energy.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 2000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 4, mag: 4 } },
    },
    {
      id: 'battle-staff_001',
      slug: 'battle-staff',
      name: 'Battle Staff',
      description: 'A war-forged staff that strikes hard and crackles with arcane power.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 2000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 6, mag: 6 } },
    },
    {
      id: 'dual-tomahawk_001',
      slug: 'dual-tomahawk',
      name: 'Dual Tomahawk',
      description: 'Two tomahawks wielded together in a whirlwind of steel and magic.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 5000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 9, mag: 9 } },
    },
    {
      id: 'nunchaku_001',
      slug: 'nunchaku',
      name: 'Nunchaku',
      description: 'Two hardwood rods connected by chain. Deceptively powerful in skilled hands.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 20000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 13, mag: 13 } },
    },
    {
      id: 'polearm_001',
      slug: 'polearm',
      name: 'Polearm',
      description: 'A versatile pole weapon combining a spear and axe head. Exceptional reach and defense.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 5000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 16, def: 20 } },
    },
    {
      id: 'bone-knuckles_001',
      slug: 'bone-knuckles',
      name: 'Bone Knuckles',
      description: 'Fearsome gauntlets crafted from monster bone. Devastating in close combat.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 15000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 25, mag: 5, def: 5 } },
    },
    {
      id: 'bone-cudgel_001',
      slug: 'bone-cudgel',
      name: 'Bone Cudgel',
      description: 'A giant bone wielded as a club. Crushes enemies but saps magic and leaves you exposed.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 8000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 35, mag: -10, def: -10 } },
    },
    {
      id: 'hammerhead-hammer_001',
      slug: 'hammerhead-hammer',
      name: 'Hammerhead Hammer',
      description: 'A colossal warhammer of legend. Its sheer mass makes it nearly unstoppable.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 50000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.MELEE,
      metadata: { isTwoHanded: true, statMods: { str: 35, mag: 10, def: 35 } },
    },
    {
      id: 'red-mini-shield_001',
      slug: 'red-mini-shield',
      name: 'Red Mini Shield',
      description: 'A small red shield that bolsters strength and toughness.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 200,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { str: 1, def: 1 } },
    },
    {
      id: 'green-mini-shield_001',
      slug: 'green-mini-shield',
      name: 'Green Mini Shield',
      description: 'A small green shield that enhances agility and defense.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 200,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { dex: 3, def: 3 } },
    },
    {
      id: 'blue-mini-shield_001',
      slug: 'blue-mini-shield',
      name: 'Blue Mini Shield',
      description: 'A small blue shield imbued with arcane energy.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 200,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { mag: 1, def: 1 } },
    },
    {
      id: 'starter-orb_001',
      slug: 'starter-orb',
      name: 'Starter Orb',
      description: 'A balanced orb that provides a small boost to all combat abilities.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 1000,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { str: 1, dex: 1, mag: 1, def: 1 } },
    },
    {
      id: 'training-shield_001',
      slug: 'training-shield',
      name: 'Training Shield',
      description: 'A lightweight shield used for learning basic blocking techniques.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 50,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { def: 3 } },
    },
    {
      id: 'buckler_001',
      slug: 'buckler',
      name: 'Buckler',
      description: 'A small round shield that allows for quick parries.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 200,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { str: 2, def: 5 } },
    },
    {
      id: 'wooden-shield_001',
      slug: 'wooden-shield',
      name: 'Wooden Shield',
      description: 'A thick wooden shield offering solid protection against physical attacks.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 200,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { def: 13 } },
    },
    {
      id: 'kite-shield_001',
      slug: 'kite-shield',
      name: 'Kite Shield',
      description: 'A large kite-shaped shield with exceptional coverage. Its bulk hampers agility and spellcasting.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 400,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { dex: -5, mag: -5, def: 20 } },
    },
    {
      id: 'hunter-shield_001',
      slug: 'hunter-shield',
      name: 'Hunter Shield',
      description: 'A versatile shield used by rangers. Light enough to maintain agility without sacrificing protection.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 1000,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { str: 3, dex: 3, def: 10 } },
    },
    {
      id: 'off-hand-dagger_001',
      slug: 'off-hand-dagger',
      name: 'Off Hand Dagger',
      description: 'A dagger held in the off hand for quick follow-up strikes.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 3000,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { str: 5 } },
    },
    {
      id: 'tower-shield_001',
      slug: 'tower-shield',
      name: 'Tower Shield',
      description: 'An enormous shield that covers the full body. Provides exceptional defense and channels magic.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 3000,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { mag: 2, def: 12 } },
    },
    {
      id: 'glowing-orb_001',
      slug: 'glowing-orb',
      name: 'Glowing Orb',
      description: 'A softly glowing orb that amplifies magical ability.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 3000,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { mag: 3 } },
    },
    {
      id: 'enchanted-orb_001',
      slug: 'enchanted-orb',
      name: 'Enchanted Orb',
      description: 'A pulsing orb crackling with enchantments. Greatly enhances magical power.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 5000,
      equipSlot: EquipSlot.OFF_HAND,
      metadata: { statMods: { mag: 7 } },
    },
    {
      id: 'boomerang_001',
      slug: 'boomerang',
      name: 'Boomerang',
      description: 'A curved throwing weapon that returns to the wielder after striking its target.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 10000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.RANGED,
      metadata: { statMods: { dex: 3 } },
    },
    {
      id: 'chakram_001',
      slug: 'chakram',
      name: 'Chakram',
      description: 'A razor-edged spinning disc that slices through enemies and channels arcane energy.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 30000,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.RANGED,
      metadata: { statMods: { dex: 7, mag: 7 } },
    },
    {
      id: 'wooden-bow_001',
      slug: 'wooden-bow',
      name: 'Wooden Bow',
      description: 'A simple wooden bow. Reliable and easy to use for beginner archers.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 800,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.RANGED,
      metadata: { isTwoHanded: true, statMods: { dex: 8, def: 4 } },
    },
    {
      id: 'hunter-bow_001',
      slug: 'hunter-bow',
      name: 'Hunter Bow',
      description: 'A well-crafted bow favored by rangers and hunters. Accurate and sturdy.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 1500,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.RANGED,
      metadata: { isTwoHanded: true, statMods: { dex: 9, def: 9 } },
    },
    {
      id: 'short-bow_001',
      slug: 'short-bow',
      name: 'Short Bow',
      description: 'A compact bow ideal for quick shots. Has a touch of magic in its carved limbs.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 1500,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.RANGED,
      metadata: { isTwoHanded: true, statMods: { dex: 9, mag: 2 } },
    },
    {
      id: 'long-bow_001',
      slug: 'long-bow',
      name: 'Long Bow',
      description: 'A tall powerful bow with exceptional range and piercing force.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 1500,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.RANGED,
      metadata: { isTwoHanded: true, statMods: { dex: 11 } },
    },
    {
      id: 'crossbow_001',
      slug: 'crossbow',
      name: 'Crossbow',
      description: 'A mechanical ranged weapon with a trigger mechanism. High precision at distance.',
      type: ItemType.EQUIPMENT,
      maxStack: 1,
      maxPerPlayer: 1,
      value: 1200,
      equipSlot: EquipSlot.MAIN_HAND,
      weaponCategory: WeaponCategory.RANGED,
      metadata: { isTwoHanded: true, statMods: { dex: 13 } },
    },
  ]

  for (const item of itemTemplates) {
    const { id, ...updateData } = item
    await prisma.itemTemplate.upsert({
      where: { slug: item.slug },
      update: updateData,
      create: item,
    })
  }

  // Seed room items (idempotent)
  await prisma.roomItem.deleteMany({
    where: { roomId: '001', templateId: 'welcome-book' },
  })

  await prisma.roomItem.create({
    data: {
      roomId: '001',
      templateId: 'welcome-book',
      quantity: 1,
      autoRespawn: true,
    },
  })

  // Seed shovel in room 006 (idempotent)
  await prisma.roomItem.deleteMany({
    where: { roomId: '006', templateId: 'shovel_001' },
  })

  await prisma.roomItem.create({
    data: {
      roomId: '006',
      templateId: 'shovel_001',
      quantity: 1,
      autoRespawn: true,
    },
  })

  // Seed flower in room 004 (idempotent)
  await prisma.roomItem.deleteMany({
    where: { roomId: '004', templateId: 'flower_001' },
  })

  await prisma.roomItem.create({
    data: {
      roomId: '004',
      templateId: 'flower_001',
      quantity: 1,
      autoRespawn: true,
    },
  })

  // Seed short sword in room 007 (idempotent)
  await prisma.roomItem.deleteMany({
    where: { roomId: '007', templateId: 'short-sword_001' },
  })

  await prisma.roomItem.create({
    data: {
      roomId: '007',
      templateId: 'short-sword_001',
      quantity: 1,
      autoRespawn: true,
    },
  })

  // Seed equipment items in room 020 (idempotent)
  const room020Items = [
    'mace_001',
    'bo_001',
    'basic-shield_001',
    'blue-hood_001',
    'padded-armor_001',
    'black-gloves_001',
    'black-boots_001',
  ]

  for (const templateId of room020Items) {
    await prisma.roomItem.deleteMany({
      where: { roomId: '020', templateId },
    })

    await prisma.roomItem.create({
      data: {
        roomId: '020',
        templateId,
        quantity: 1,
        autoRespawn: true,
      },
    })
  }

  // Remove weapons no longer placed in room 088
  await prisma.roomItem.deleteMany({
    where: {
      roomId: '088',
      templateId: { in: ['nunchaku_001', 'three-chained-flail_001', 'gray-wand_001', 'demon-dagger_001', 'bastard-sword_001'] },
    },
  })

  // Seed weapons in room 088 - Solar Office (idempotent)
  const room088Items = [
    'master-sword_001',
    'great-white-sword_001',
    'hammerhead-hammer_001',
    'bone-cudgel_001',
    'bone-knuckles_001',
    'great-sword_001',
    'boomerang_001',
    'chakram_001',
    'wooden-bow_001',
    'hunter-bow_001',
    'short-bow_001',
    'long-bow_001',
    'crossbow_001',
    'red-mini-shield_001',
    'green-mini-shield_001',
    'blue-mini-shield_001',
    'starter-orb_001',
    'training-shield_001',
    'basic-shield_001',
    'buckler_001',
    'wooden-shield_001',
    'kite-shield_001',
    'hunter-shield_001',
    'off-hand-dagger_001',
    'tower-shield_001',
    'glowing-orb_001',
    'enchanted-orb_001',
  ]

  for (const templateId of room088Items) {
    await prisma.roomItem.deleteMany({
      where: { roomId: '088', templateId },
    })

    await prisma.roomItem.create({
      data: {
        roomId: '088',
        templateId,
        quantity: 1,
        autoRespawn: true,
      },
    })
  }

  // Create a test user
  const hashedPassword = await bcrypt.hash('password123', 12)
  
  const testUser = await prisma.user.upsert({
    where: { username: 'testuser' },
    update: {},
    create: {
      username: 'testuser',
      password: hashedPassword,
      email: 'test@example.com',
      currentRoom: '000',
      level: 1,
      hp: 10,
      hpMax: 10,
      mp: 2,
      mpMax: 2,
      str: 10,
      dex: 10,
      mag: 10,
      def: 10,
      equipment: {
        create: {}
      }
    }
  })

  console.log('✅ Database seeded successfully!')
  console.log(`👤 Test user created: ${testUser.username} (password: password123)`)
  console.log(`🏠 Created ${rooms.length} rooms`)
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
