/**
 * Writes src/lib/game-data/bosses.generated.js: the enemies tagged `rank`
 * (boss or miniboss) in enemies.js, cut down to what the browser needs to draw
 * one — portrait, stats, perk flags, lair — without the descriptions, drop
 * tables and rewards of all 180 enemies (enemies.js is 145 KB; this is a few).
 *
 * Run: npm run generate-bosses   (dev and build run it for you)
 * test/boss-teleports.test.js fails when the file is stale.
 */
const fs = require('fs')
const path = require('path')
const { ENEMIES } = require('../src/lib/game-data/enemies')

/** What stays off the record: prose, loot and rewards. Everything else rides. */
const OMIT = new Set(['description', 'drops', 'xpReward', 'goldMin', 'goldMax'])

function buildBosses(enemies = ENEMIES) {
  return enemies
    .filter((enemy) => enemy.rank)
    .map((enemy) => Object.fromEntries(Object.entries(enemy).filter(([key]) => !OMIT.has(key))))
}

function render(bosses) {
  const rows = bosses.map((boss) => `  ${JSON.stringify(boss)},`).join('\n')
  return `// GENERATED by scripts/generate-bosses.js from enemies.js — do not edit.
// The enemies tagged \`rank\` (boss / miniboss), minus prose, loot and rewards,
// so the browser can draw a boss without the whole enemy registry.
const BOSSES = [
${rows}
]

module.exports = { BOSSES }
`
}

const OUT = path.join(__dirname, '../src/lib/game-data/bosses.generated.js')

if (require.main === module) {
  fs.writeFileSync(OUT, render(buildBosses()))
  console.log(`bosses: wrote ${buildBosses().length} to ${path.relative(process.cwd(), OUT)}`)
}

module.exports = { buildBosses, render, OUT }
