// Drop system shape:
//   drops.main      — mutually-exclusive weighted roll: at most ONE item drops per kill.
//                     `chance` values are laid end-to-end; if they sum to < 1.0 the remainder is "no drop".
//                     A winning entry drops qty 1 unless it carries `qty` (fixed) or `min`/`max`
//                     (random qty rolled in [min, max] inclusive).
//   drops.always    — items that drop on EVERY kill (in addition to the main roll). Each entry is
//                     either a slug string (qty 1), { itemSlug, qty } (fixed qty), or
//                     { itemSlug, min, max } (random qty rolled in [min, max] inclusive).
//   drops.firstKill — array of slugs that drop while the player does NOT already own the item.
//                     Typically earned on the first kill, but re-drops on later kills if the
//                     player no longer holds the item (sold/dropped), and stops once owned again.
//
// specials — optional array of enemy perk ids (see game-data/enemy-specials.js), e.g.
//            `specials: ['power']`. Each perk's proc chance and damage rule live in that
//            registry; the enemy only declares which it carries. Omit the field entirely
//            for enemies that just attack normally.
const STANDARD_MAIN_DROP = [
  { itemSlug: 'redberry', chance: 0.25 },
  { itemSlug: 'blueberry', chance: 0.25 },
  { itemSlug: 'red-potion', chance: 0.25 },
  { itemSlug: 'raw-meat', chance: 0.25 },
]

const ENEMIES = [
  {
    slug: 'rat',
    zone: 'Grassy Field',
    name: 'Rat',
    description: 'A scraggly vermin with yellowed teeth.',
    icon: 'enemy-Rat',
    level: 1,
    hp: 3,
    att: 1,
    def: 1,
    isAggressive: false,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 1,
    goldMin: 1,
    goldMax: 3,
    drops: {
      main: [
        { itemSlug: 'string', chance: 0.25 },
        { itemSlug: 'redberry', chance: 0.25, min: 1, max: 2 },
        { itemSlug: 'dagger', chance: 0.25 },
        { itemSlug: 'blueberry', chance: 0.25 },
      ],
      always: [{ itemSlug: 'raw-meat', qty: 1 }],
    },
  },
  {
    slug: 'sand-crab',
    zone: 'Grassy Field',
    name: 'Sand Crab',
    description: 'A large crab with a hardened shell, scuttling sideways across the sand.',
    icon: 'enemy-SandCrab',
    level: 2,
    hp: 3,
    att: 2,
    def: 2,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 2,
    goldMin: 1,
    goldMax: 2,
    drops: { main: STANDARD_MAIN_DROP, firstKill: ['training-helmet'], always: [{ itemSlug: 'raw-meat', qty: 1 }] },
  },
  {
    slug: 'giant-rat',
    zone: 'Grassy Field',
    name: 'Giant Rat',
    description: 'A massive, foul-smelling rodent with red eyes.',
    icon: 'enemy-GiantRat',
    level: 3,
    hp: 6,
    att: 3,
    def: 1,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 3,
    goldMin: 3,
    goldMax: 8,
    drops: {
      main: [
        { itemSlug: 'ring-of-def', chance: 0.25 },
        { itemSlug: 'redberry', chance: 0.25, min: 1, max: 3 },
        { itemSlug: 'blueberry', chance: 0.25, min: 1, max: 2 },
        { itemSlug: 'red-potion', chance: 0.25 },
      ],
      always: [{ itemSlug: 'raw-meat', min: 1, max: 3 }],
    },
  },
  {
    slug: 'gator',
    zone: 'Grassy Field',
    name: 'Gator',
    description: 'A massive reptile lurking in the marsh, coiled and ready to strike.',
    icon: 'enemy-Gator',
    level: 5,
    hp: 100,
    att: 8,
    def: 0,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 20,
    goldMin: 10,
    goldMax: 100,
    drops: {
      main: [
        { itemSlug: 'padded-armor', chance: 0.25 },
        { itemSlug: 'club', chance: 0.25 },
        { itemSlug: 'ring-of-str', chance: 0.25 },
        { itemSlug: 'ring-of-def', chance: 0.25 },
      ],
      firstKill: ['training-armor'],
      always: [{ itemSlug: 'raw-meat', qty: 5 }],
    },
  },
  {
    slug: 'spider',
    zone: 'Spider Cave',
    name: 'Spider',
    description: 'A skittering cave spider with venom-tipped fangs.',
    icon: 'enemy-Spider',
    level: 2,
    hp: 5,
    att: 3,
    def: 1,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 2,
    goldMin: 1,
    goldMax: 5,
    drops: {
      main: [
        { itemSlug: 'raw-meat', chance: 0.25, qty: 2 },
        { itemSlug: 'basic-shield', chance: 0.25 },
        { itemSlug: 'redberry', chance: 0.25, qty: 2 },
        { itemSlug: 'blueberry', chance: 0.25, qty: 2 },
      ],
      always: ['scorpion-tail'],
      firstKill: ['training-gloves'],
    },
  },
  {
    slug: 'scorpion',
    zone: 'Spider Cave',
    name: 'Scorpion',
    description: 'An armored scorpion with a barbed tail poised to strike.',
    icon: 'enemy-Scorpion',
    level: 3,
    hp: 8,
    att: 5,
    def: 2,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 4,
    goldMin: 2,
    goldMax: 10,
    drops: {
      main: [
        { itemSlug: 'dagger', chance: 0.25 },
        { itemSlug: 'blueberry', chance: 0.25, qty: 2 },
        { itemSlug: 'basic-staff', chance: 0.25 },
        { itemSlug: 'basic-hood', chance: 0.25 },
      ],
      always: ['scorpion-tail'],
      firstKill: ['training-boots'],
    },
  },
  {
    slug: 'giant-spider',
    zone: 'Spider Cave',
    name: 'Giant Spider',
    description: 'A massive spider that fills the tunnel with its sprawling legs.',
    icon: 'enemy-GiantSpider',
    level: 4,
    hp: 10,
    att: 6,
    def: 3,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 6,
    goldMin: 5,
    goldMax: 10,
    drops: {
      main: [
        { itemSlug: 'red-boots', chance: 0.25 },
        { itemSlug: 'mace', chance: 0.25 },
        { itemSlug: 'redberry', chance: 0.25, min: 2, max: 6 },
        { itemSlug: 'broad-sword', chance: 0.25 },
      ],
      always: ['scorpion-tail'],
    },
  },
  {
    slug: 'alpha-scorpion',
    zone: 'Spider Cave',
    name: 'Alpha Scorpion',
    description: 'A colossal scorpion, larger and more lethal than any of its kin.',
    icon: 'enemy-AlphaScorpion',
    level: 5,
    hp: 20,
    att: 8,
    def: 5,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 8,
    goldMin: 10,
    goldMax: 20,
    drops: {
      main: [
        { itemSlug: 'basic-hood', chance: 0.25 },
        { itemSlug: 'red-hood', chance: 0.25 },
        { itemSlug: 'green-hood', chance: 0.25 },
        { itemSlug: 'blue-hood', chance: 0.25 },
      ],
      always: [{ itemSlug: 'scorpion-tail', qty: 2 }],
      firstKill: ['long-sword'],
    },
  },
  {
    slug: 'scorpion-guard',
    zone: 'Scorpion Pit',
    name: 'Scorpion Guard',
    description: 'A disciplined scorpion hardened by pit combat, standing watch at the dungeon\'s edge.',
    icon: 'enemy-ScorpionGuard',
    level: 7,
    hp: 30,
    att: 10,
    def: 8,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 10,
    goldMin: 20,
    goldMax: 30,
    drops: {
      main: [
        { itemSlug: 'red-potion', chance: 0.25, min: 2, max: 4 },
        { itemSlug: 'club', chance: 0.25 },
        { itemSlug: 'kite-shield', chance: 0.25 },
        { itemSlug: 'basic-helmet', chance: 0.25 },
      ],
      always: [{ itemSlug: 'scorpion-tail', qty: 3 }],
    },
  },
  {
    slug: 'mammoth-scorpion',
    zone: 'Scorpion Pit',
    name: 'Mammoth Scorpion',
    description: 'An enormous scorpion whose armored bulk fills the tunnel. Its tail strike shakes the walls.',
    icon: 'enemy-MammothScorpion',
    level: 10,
    hp: 70,
    att: 20,
    def: 16,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 25,
    goldMin: 30,
    goldMax: 60,
    drops: {
      main: [
        { itemSlug: 'ring-of-str', chance: 0.25 },
        { itemSlug: 'blue-potion', chance: 0.25, min: 2, max: 4 },
        { itemSlug: 'tower-shield', chance: 0.25 },
        { itemSlug: 'padded-armor', chance: 0.25 },
      ],
      always: [{ itemSlug: 'scorpion-tail', qty: 4 }],
    },
  },
  {
    slug: 'scorpion-queen',
    zone: 'Scorpion Pit',
    name: 'Scorpion Queen',
    description: 'The matriarch of the pit. Her venom dissolves stone and her rage is absolute.',
    icon: 'enemy-ScorpionQueen',
    level: 15,
    hp: 200,
    att: 50,
    def: 40,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 150,
    goldMin: 200,
    goldMax: 500,
    drops: { main: STANDARD_MAIN_DROP, always: [{ itemSlug: 'scorpion-tail', qty: 5 }] },
  },
  {
    slug: 'scorpion-king',
    zone: 'Scorpion Pit',
    name: 'Scorpion King',
    description: 'The apex predator of the dungeon. Ancient, enormous, and merciless — none who have faced him have returned.',
    icon: 'enemy-ScorpionKing',
    level: 30,
    hp: 500,
    att: 100,
    def: 80,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 300,
    goldMin: 500,
    goldMax: 1000,
    drops: { main: STANDARD_MAIN_DROP, always: [{ itemSlug: 'scorpion-tail', qty: 10 }] },
  },
  {
    slug: 'bat',
    zone: 'Bat Cave',
    name: 'Bat',
    description: 'A leathery-winged bat that swoops from the cavern shadows with shrill, piercing cries.',
    icon: 'enemy-Bat',
    level: 2,
    hp: 3,
    att: 2,
    def: 2,
    isAggressive: true,
    isFriendly: false,
    isFlying: true,
    damageType: 'MELEE',
    xpReward: 3,
    goldMin: 5,
    goldMax: 20,
    drops: {
      always: ['bat-wing'],
      main: [
        { itemSlug: 'blueberry', chance: 0.25, min: 1, max: 3 },
        { itemSlug: 'long-sword', chance: 0.25 },
        { itemSlug: 'arrow', chance: 0.25, min: 2, max: 5 },
        { itemSlug: 'crossbow-bolt', chance: 0.25, min: 2, max: 5 },
      ],
    },
  },
  {
    slug: 'golden-bat',
    zone: 'Bat Cave',
    name: 'Golden Bat',
    description: 'A rare bat with shimmering gold-flecked fur. Faster and far more vicious than its lesser kin.',
    icon: 'enemy-GoldenBat',
    level: 6,
    hp: 20,
    att: 8,
    def: 2,
    isAggressive: true,
    isFriendly: false,
    isFlying: true,
    damageType: 'MELEE',
    xpReward: 10,
    goldMin: 100,
    goldMax: 300,
    drops: {
      always: [{ itemSlug: 'bat-wing', qty: 2 }],
      main: [
        { itemSlug: 'red-potion', chance: 0.25, min: 1, max: 3 },
        { itemSlug: 'green-gloves', chance: 0.25 },
        { itemSlug: 'blue-potion', chance: 0.25, min: 1, max: 3 },
        { itemSlug: 'ring-of-dex', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'salamander',
    zone: 'Bat Cave',
    name: 'Salamander',
    description: 'A thick-bodied cave salamander with damp, mottled skin and a sluggish but punishing bite.',
    icon: 'enemy-Salamander',
    level: 6,
    hp: 30,
    att: 10,
    def: 6,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 9,
    goldMin: 5,
    goldMax: 30,
    drops: {
      always: ['raw-meat'],
      main: [
        { itemSlug: 'blueberry', chance: 0.25, min: 5, max: 15 },
        { itemSlug: 'bo-staff', chance: 0.25 },
        { itemSlug: 'arrow', chance: 0.25, min: 5, max: 15 },
        { itemSlug: 'ring-of-mag', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'goblin',
    zone: 'Bat Cave',
    name: 'Goblin',
    description: 'A wiry green-skinned goblin clutching a crude blade. Snarls and lunges without warning.',
    icon: 'enemy-Goblin',
    level: 5,
    hp: 20,
    att: 8,
    def: 6,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 7,
    goldMin: 5,
    goldMax: 10,
    drops: {
      main: [
        { itemSlug: 'redberry', chance: 0.25, min: 5, max: 15 },
        { itemSlug: 'dagger', chance: 0.25 },
        { itemSlug: 'basic-helmet', chance: 0.25 },
        { itemSlug: 'black-gloves', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'goblin-bandit',
    zone: 'Bat Cave',
    name: 'Goblin Bandit',
    description: 'A scarred goblin wrapped in stolen leathers, wielding a notched short blade with practiced cruelty.',
    icon: 'enemy-GoblinBandit',
    level: 7,
    hp: 40,
    att: 12,
    def: 8,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 12,
    goldMin: 20,
    goldMax: 40,
    drops: {
      main: [
        { itemSlug: 'buckler', chance: 0.25 },
        { itemSlug: 'red-hood', chance: 0.0625 },
        { itemSlug: 'blue-hood', chance: 0.0625 },
        { itemSlug: 'green-hood', chance: 0.0625 },
        { itemSlug: 'basic-hood', chance: 0.0625 },
        { itemSlug: 'wrist-bracers', chance: 0.25 },
        { itemSlug: 'black-boots', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'goblin-chief',
    zone: 'Bat Cave',
    name: 'Goblin Chief',
    description: 'The brutal warlord of the goblin tribe. Massive for his kind, draped in bone trophies and roaring for blood.',
    icon: 'enemy-GoblinChief',
    level: 10,
    hp: 120,
    att: 20,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 30,
    goldMin: 100,
    goldMax: 200,
    drops: {
      main: [
        { itemSlug: 'long-bow', chance: 0.25 },
        { itemSlug: 'warhammer', chance: 0.25 },
        { itemSlug: 'flail', chance: 0.25 },
        { itemSlug: 'morning-star', chance: 0.25 },
      ],
      firstKill: ['goblin-cloak'],
    },
  },
  // ==================== FOREST PATH ====================
  {
    slug: 'cow',
    zone: 'Forest Path',
    name: 'Cow',
    description: 'A docile cow grazing in the field. It moos at you disinterestedly.',
    icon: 'enemy-Cow',
    level: 4,
    hp: 20,
    att: 5,
    def: 5,
    isAggressive: false,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 5,
    goldMin: 2,
    goldMax: 5,
    drops: {
      main: [
        { itemSlug: 'raw-meat', chance: 0.25 },
        { itemSlug: 'redberry', chance: 0.50, qty: 2 },
        { itemSlug: 'blueberry', chance: 0.25 },
      ],
      always: ['raw-meat'],
    },
  },
  {
    slug: 'wild-boar',
    zone: 'Forest Path',
    name: 'Wild Boar',
    description: 'A tusked boar rooting through the underbrush. It charges without warning.',
    icon: 'enemy-WildBoar',
    level: 5,
    hp: 40,
    att: 8,
    def: 5,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 8,
    goldMin: 10,
    goldMax: 20,
    drops: {
      main: [
        { itemSlug: 'redberry', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'blueberry', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'raw-meat', chance: 0.25, qty: 3 },
        { itemSlug: 'red-potion', chance: 0.25 },
      ],
      always: [{ itemSlug: 'raw-meat', qty: 2 }],
    },
  },
  {
    slug: 'snake',
    zone: 'Forest Path',
    name: 'Snake',
    description: 'A venomous snake coiled among the leaves. Fast and deadly.',
    icon: 'enemy-Snake',
    level: 5,
    hp: 15,
    att: 15,
    def: 5,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 8,
    goldMin: 10,
    goldMax: 20,
    drops: {
      main: [
        { itemSlug: 'raw-meat', chance: 0.25, qty: 3 },
        { itemSlug: 'blueberry', chance: 0.25, min: 10, max: 20 },
        { itemSlug: 'red-potion', chance: 0.25, qty: 3 },
        { itemSlug: 'redberry', chance: 0.25, min: 5, max: 10 },
      ],
    },
  },
  {
    slug: 'thief',
    zone: 'Forest Path',
    name: 'Thief',
    description: 'A hooded figure lurking in the shadows, waiting to relieve you of your gold.',
    icon: 'enemy-Thief',
    level: 5,
    hp: 20,
    att: 10,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 10,
    goldMin: 5,
    goldMax: 20,
    drops: {
      main: [
        { itemSlug: 'long-sword', chance: 0.25 },
        { itemSlug: 'black-gloves', chance: 0.25 },
        { itemSlug: 'crossbow-bolt', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'ring-of-str', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'hob-goblin',
    zone: 'Ogre Lair',
    name: 'Hob Goblin',
    description: 'A hulking goblin with crude armor and a vicious temper. Bigger and meaner than its lesser kin.',
    icon: 'enemy-HobGoblin',
    level: 6,
    hp: 30,
    att: 9,
    def: 7,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 9,
    goldMin: 10,
    goldMax: 20,
    drops: {
      main: [
        { itemSlug: 'blueberry', chance: 0.25, min: 1, max: 3 },
        { itemSlug: 'green-gloves', chance: 0.25 },
        { itemSlug: 'wooden-bow', chance: 0.25 },
        { itemSlug: 'arrow', chance: 0.25, min: 5, max: 10 },
      ],
    },
  },
  {
    slug: 'orc',
    zone: 'Ogre Lair',
    name: 'Orc',
    description: 'A muscular green-skinned warrior wielding a jagged blade. Fights with savage precision.',
    icon: 'enemy-Orc',
    level: 7,
    hp: 40,
    att: 11,
    def: 7,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'RANGED',
    xpReward: 12,
    goldMin: 15,
    goldMax: 25,
    drops: {
      main: [
        { itemSlug: 'long-sword', chance: 0.25 },
        { itemSlug: 'black-gloves', chance: 0.25 },
        { itemSlug: 'crossbow', chance: 0.25 },
        { itemSlug: 'crossbow-bolt', chance: 0.25, min: 5, max: 10 },
      ],
    },
  },
  {
    slug: 'ogre',
    zone: 'Ogre Lair',
    name: 'Ogre',
    description: 'A massive, lumbering brute with a club the size of a tree trunk.',
    icon: 'enemy-Ogre',
    level: 8,
    hp: 50,
    att: 15,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 20,
    goldMin: 20,
    goldMax: 30,
    drops: {
      main: [
        { itemSlug: 'warhammer', chance: 0.25 },
        { itemSlug: 'flail', chance: 0.25 },
        { itemSlug: 'wrist-bracers', chance: 0.25 },
        { itemSlug: 'leather-helmet', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'kobold',
    zone: 'Kobold Lair',
    name: 'Kobold',
    description: 'A small reptilian creature crackling with magical energy. Deceptively dangerous.',
    icon: 'enemy-Kobold',
    level: 7,
    hp: 30,
    att: 10,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MAGIC',
    xpReward: 10,
    goldMin: 15,
    goldMax: 25,
    drops: {
      main: [
        { itemSlug: 'blueberry', chance: 0.25, min: 2, max: 6 },
        { itemSlug: 'redberry', chance: 0.25, min: 2, max: 6 },
        { itemSlug: 'long-sword', chance: 0.25 },
        { itemSlug: 'kite-shield', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'skeleton',
    zone: 'Forest Path',
    name: 'Skeleton',
    description: 'An animated skeleton that rattles along the path, its empty eyes burning with pale light.',
    icon: 'enemy-Skeleton',
    level: 7,
    hp: 40,
    att: 15,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 12,
    goldMin: 10,
    goldMax: 25,
    drops: {
      main: [
        { itemSlug: 'long-sword', chance: 0.25 },
        { itemSlug: 'crossbow-bolt', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'red-potion', chance: 0.25 },
        { itemSlug: 'ring-of-def', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'imp',
    zone: 'Forest Path',
    name: 'Imp',
    description: 'A tiny, cackling demon that darts and dodges with unnatural speed. Hard to hit, harder to catch.',
    icon: 'enemy-Imp',
    level: 7,
    hp: 10,
    att: 25,
    def: 25,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 30,
    goldMin: 20,
    goldMax: 50,
    drops: {
      main: [
        { itemSlug: 'demon-dagger', chance: 0.25 },
        { itemSlug: 'redberry', chance: 0.25, min: 5, max: 15 },
        { itemSlug: 'dual-tomahawk', chance: 0.25 },
        { itemSlug: 'blue-potion', chance: 0.25 },
      ],
    },
  },
  // ==================== FOREST ====================
  {
    slug: 'wolf',
    zone: 'Forest',
    name: 'Wolf',
    description: 'A lean gray wolf stalking through the underbrush. Its eyes glow in the dim forest light.',
    icon: 'enemy-Wolf',
    level: 5,
    hp: 40,
    att: 12,
    def: 5,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 15,
    goldMin: 5,
    goldMax: 10,
    drops: {
      main: [
        { itemSlug: 'redberry', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'raw-meat', chance: 0.25, qty: 2 },
        { itemSlug: 'red-potion', chance: 0.25, qty: 3 },
        { itemSlug: 'blue-potion', chance: 0.25, qty: 3 },
      ],
      always: ['raw-meat'],
    },
  },
  {
    slug: 'coyote',
    zone: 'Forest',
    name: 'Coyote',
    description: 'A wiry coyote with matted fur and cunning eyes. It circles you, looking for an opening.',
    icon: 'enemy-Coyote',
    level: 6,
    hp: 40,
    att: 15,
    def: 5,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 20,
    goldMin: 5,
    goldMax: 15,
    drops: {
      main: [
        { itemSlug: 'blueberry', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'raw-meat', chance: 0.25, qty: 2 },
        { itemSlug: 'leather-hood', chance: 0.25 },
        { itemSlug: 'ring-of-dex', chance: 0.25 },
      ],
      always: ['raw-meat'],
    },
  },
  {
    slug: 'buck',
    zone: 'Forest',
    name: 'Buck',
    description: 'A powerful buck with a full rack of antlers. It lowers its head and charges.',
    icon: 'enemy-Buck',
    level: 6,
    hp: 60,
    att: 15,
    def: 8,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 25,
    goldMin: 10,
    goldMax: 20,
    drops: {
      main: [
        { itemSlug: 'arrow', chance: 0.25, min: 10, max: 20 },
        { itemSlug: 'raw-meat', chance: 0.25, min: 1, max: 2 },
        { itemSlug: 'leather-armor', chance: 0.25 },
        { itemSlug: 'red-potion', chance: 0.25 },
      ],
      always: ['raw-meat'],
    },
  },
  {
    slug: 'stag',
    zone: 'Forest',
    name: 'Stag',
    description: 'A majestic stag with silver-tipped antlers. An aura of ancient power surrounds it.',
    icon: 'enemy-Stag',
    level: 8,
    hp: 80,
    att: 20,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 30,
    goldMin: 20,
    goldMax: 40,
    drops: {
      main: [
        { itemSlug: 'arrow', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'gray-hood', chance: 0.25 },
        { itemSlug: 'raw-meat', chance: 0.25, qty: 2 },
        { itemSlug: 'blue-potion', chance: 0.25 },
      ],
      always: ['raw-meat'],
    },
  },
  {
    slug: 'bear',
    zone: 'Forest',
    name: 'Bear',
    description: 'A massive brown bear standing on its hind legs. Its roar shakes the trees.',
    icon: 'enemy-Bear',
    level: 8,
    hp: 100,
    att: 25,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 30,
    goldMin: 30,
    goldMax: 50,
    drops: {
      main: [
        { itemSlug: 'crossbow-bolt', chance: 0.25, min: 5, max: 15 },
        { itemSlug: 'ring-of-str', chance: 0.25 },
        { itemSlug: 'raw-meat', chance: 0.25, min: 2, max: 4 },
        { itemSlug: 'red-potion', chance: 0.25, qty: 3 },
      ],
      always: [{ itemSlug: 'raw-meat', qty: 2 }],
    },
  },
  {
    slug: 'bigfoot',
    zone: 'Forest',
    name: 'Bigfoot',
    description: 'A towering, shaggy creature that smells of pine and fury. Few have seen one and lived.',
    icon: 'enemy-Bigfoot',
    level: 13,
    hp: 200,
    att: 40,
    def: 15,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 100,
    goldMin: 200,
    goldMax: 300,
    drops: {
      main: [
        { itemSlug: 'iron', chance: 0.25, min: 1, max: 3 },
        { itemSlug: 'giant-club', chance: 0.25 },
        { itemSlug: 'red-potion', chance: 0.25, qty: 3 },
        { itemSlug: 'hunter-bow', chance: 0.25 },
      ],
      always: [{ itemSlug: 'raw-meat', qty: 3 }],
    },
  },
  {
    slug: 'hawk',
    zone: 'Forest',
    name: 'Hawk',
    description: 'A massive bird of prey with razor talons. It dives from above with blinding speed.',
    icon: 'enemy-Hawk',
    level: 9,
    hp: 30,
    att: 25,
    def: 15,
    isAggressive: true,
    isFriendly: false,
    isFlying: true,
    damageType: 'MELEE',
    xpReward: 50,
    goldMin: 50,
    goldMax: 70,
    drops: {
      main: [
        { itemSlug: 'ring-of-dex', chance: 0.25 },
        { itemSlug: 'crossbow-bolt', chance: 0.25, min: 5, max: 15 },
        { itemSlug: 'red-potion', chance: 0.25, qty: 3 },
        { itemSlug: 'arrow', chance: 0.25, min: 10, max: 20 },
      ],
    },
  },
  // ==================== TROLL TERRITORY ====================
  {
    slug: 'troll',
    zone: 'Forest',
    name: 'Troll',
    description: 'A hulking forest troll with mossy green skin and enormous fists. It regenerates wounds with frightening speed.',
    icon: 'enemy-Troll',
    level: 13,
    hp: 120,
    att: 30,
    def: 15,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    specials: ['power'],
    xpReward: 50,
    goldMin: 40,
    goldMax: 80,
    drops: {
      main: [
        { itemSlug: 'red-potion', chance: 0.25, min: 1, max: 2 },
        { itemSlug: 'troll-boots', chance: 0.25 },
        { itemSlug: 'ring-of-str', chance: 0.25 },
        { itemSlug: 'hunter-bow', chance: 0.25 },
      ],
      always: [{ itemSlug: 'raw-meat', qty: 2 }],
    },
  },
  // ==================== OGRE LAIR (Forest Underground) ====================
  {
    slug: 'ogre-guard',
    zone: 'Ogre Lair',
    name: 'Ogre Guard',
    description: 'A disciplined ogre in crude iron armor. It stands watch with a massive pike.',
    icon: 'enemy-OgreGuard',
    level: 9,
    hp: 80,
    att: 20,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 25,
    goldMin: 30,
    goldMax: 40,
    drops: {
      main: [
        { itemSlug: 'pike', chance: 0.25 },
        { itemSlug: 'horned-helmet', chance: 0.25 },
        { itemSlug: 'red-potion', chance: 0.25 },
        { itemSlug: 'leather-helmet', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'fire-ogress',
    zone: 'Ogre Lair',
    name: 'Fire Ogress',
    description: 'A female ogre wreathed in flames. Her eyes glow with malice and dark magic.',
    icon: 'enemy-FireOgress',
    level: 10,
    hp: 70,
    att: 25,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MAGIC',
    xpReward: 30,
    goldMin: 40,
    goldMax: 50,
    drops: {
      main: [
        { itemSlug: 'wooden-staff', chance: 0.25 },
        { itemSlug: 'morning-star', chance: 0.25 },
        { itemSlug: 'red-potion', chance: 0.25 },
        { itemSlug: 'ring-of-mag', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'ogre-lieutenant',
    zone: 'Ogre Lair',
    name: 'Ogre Lieutenant',
    description: 'The commander of the Ogre Lair. Massive and battle-scarred, trophies of defeated warriors adorn his armor.',
    icon: 'enemy-OgreLieutenant',
    level: 13,
    hp: 250,
    att: 35,
    def: 20,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 50,
    goldMin: 100,
    goldMax: 300,
    drops: {
      main: [
        { itemSlug: 'claymore', chance: 0.25 },
        { itemSlug: 'barbarian-helmet', chance: 0.25 },
        { itemSlug: 'buckler', chance: 0.25 },
        { itemSlug: 'kite-shield', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'ogre-priest',
    zone: 'Ogre Lair',
    name: 'Ogre Priest',
    description: 'A rare and terrifying ogre shaman draped in bone fetishes. Its dark magic can heal and destroy.',
    icon: 'enemy-OgrePriest',
    level: 11,
    hp: 80,
    att: 30,
    def: 20,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MAGIC',
    xpReward: 50,
    goldMin: 200,
    goldMax: 400,
    drops: {
      main: [
        { itemSlug: 'nunchaku', chance: 0.25 },
        { itemSlug: 'chakram', chance: 0.25 },
        { itemSlug: 'demon-dagger', chance: 0.25 },
        { itemSlug: 'blue-potion', chance: 0.25, qty: 2 },
      ],
    },
  },
  // ==================== KOBOLD LAIR (Forest Underground) ====================
  {
    slug: 'flying-kobold',
    zone: 'Kobold Lair',
    name: 'Flying Kobold',
    description: 'A winged kobold that swoops through the cavern darkness, striking from above.',
    icon: 'enemy-FlyingKobold',
    level: 7,
    hp: 30,
    att: 10,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: true,
    damageType: 'MELEE',
    xpReward: 15,
    goldMin: 15,
    goldMax: 25,
    drops: {
      main: [
        { itemSlug: 'wooden-bow', chance: 0.25 },
        { itemSlug: 'arrow', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'crossbow', chance: 0.25 },
        { itemSlug: 'crossbow-bolt', chance: 0.25, min: 5, max: 10 },
      ],
    },
  },
  {
    slug: 'kobold-shaman',
    zone: 'Kobold Lair',
    name: 'Kobold Shaman',
    description: 'A kobold draped in fetishes and glowing runes. Its magic crackles through the air.',
    icon: 'enemy-KoboldShaman',
    level: 8,
    hp: 40,
    att: 15,
    def: 4,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MAGIC',
    xpReward: 20,
    goldMin: 30,
    goldMax: 60,
    drops: {
      main: [
        { itemSlug: 'gray-boots', chance: 0.25 },
        { itemSlug: 'bo-staff', chance: 0.25 },
        { itemSlug: 'ring-of-mag', chance: 0.25 },
        { itemSlug: 'red-hood', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'kobold-ninja',
    zone: 'Kobold Lair',
    name: 'Kobold Ninja',
    description: 'A kobold cloaked in shadow, wielding twin blades with lethal precision.',
    icon: 'enemy-KoboldNinja',
    level: 8,
    hp: 40,
    att: 20,
    def: 8,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 20,
    goldMin: 40,
    goldMax: 80,
    drops: {
      main: [
        { itemSlug: 'wooden-bo', chance: 0.25 },
        { itemSlug: 'samurai-sword', chance: 0.25 },
        { itemSlug: 'arrow', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'ring-of-dex', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'kobold-warlock',
    zone: 'Kobold Lair',
    name: 'Kobold Warlock',
    description: 'A kobold sorcerer wreathed in dark energy. Its spells strike with devastating force.',
    icon: 'enemy-KoboldWarlock',
    level: 9,
    hp: 50,
    att: 25,
    def: 4,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MAGIC',
    xpReward: 25,
    goldMin: 30,
    goldMax: 80,
    drops: {
      main: [
        { itemSlug: 'gray-gloves', chance: 0.25 },
        { itemSlug: 'black-robe', chance: 0.25 },
        { itemSlug: 'battle-staff', chance: 0.25 },
        { itemSlug: 'wand', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'kobold-champion',
    zone: 'Kobold Lair',
    name: 'Kobold Champion',
    description: 'The strongest warrior of the kobold tribe. Battle-hardened and fearless.',
    icon: 'enemy-KoboldChampion',
    level: 10,
    hp: 100,
    att: 25,
    def: 8,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 30,
    goldMin: 20,
    goldMax: 100,
    drops: {
      main: [
        { itemSlug: 'pike', chance: 0.25 },
        { itemSlug: 'green-cloak', chance: 0.25 },
        { itemSlug: 'horned-helmet', chance: 0.25 },
        { itemSlug: 'glowing-orb', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'kobold-master',
    zone: 'Kobold Lair',
    name: 'Kobold Master',
    description: 'The supreme leader of the Kobold Lair. Ancient and immensely powerful, arcane energy pours from its very being.',
    icon: 'enemy-KoboldMaster',
    level: 13,
    hp: 80,
    att: 40,
    def: 50,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MAGIC',
    xpReward: 50,
    goldMin: 50,
    goldMax: 200,
    drops: {
      main: [
        { itemSlug: 'gladius', chance: 0.25 },
        { itemSlug: 'gray-robe', chance: 0.25 },
        { itemSlug: 'blue-potion', chance: 0.25, min: 1, max: 2 },
        { itemSlug: 'dual-tomahawk', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'kobold-monk',
    zone: 'Kobold Lair',
    name: 'Kobold Monk',
    description: 'A rare kobold ascetic of immense discipline. Its martial arts and healing magic make it a deadly foe.',
    icon: 'enemy-KoboldMonk',
    level: 11,
    hp: 60,
    att: 30,
    def: 30,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MAGIC',
    xpReward: 50,
    goldMin: 200,
    goldMax: 400,
    drops: {
      main: [
        { itemSlug: 'nunchaku', chance: 0.25 },
        { itemSlug: 'chakram', chance: 0.25 },
        { itemSlug: 'demon-dagger', chance: 0.25 },
        { itemSlug: 'blue-potion', chance: 0.25, qty: 2 },
      ],
    },
  },

  // ==================== RED TOWN / SEWERS / THIEVE'S DEN / CATACOMBS ====================
  // Stats (level/hp/att/def) are ported 1:1 from the original battle-initialize.php;
  // XP and coin come from battle-win.php. Legacy drops that name items this game does
  // not have yet (javelins, dung, bone, gills/purple potions, meatballs, the "iron"
  // equipment tier and the tier-II rings) are substituted with the nearest existing
  // slug, the same way the Forest port already substituted its purple potions.
  {
    slug: 'tarantula',
    zone: 'Red Town Sewers',
    name: 'Tarantula',
    description: 'A hairy, dinner-plate-sized spider picking its way along the sewer wall.',
    icon: 'enemy-Tarantula',
    level: 7,
    hp: 50,
    att: 20,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 25,
    goldMin: 2,
    goldMax: 3,
    drops: {
      main: [
        { itemSlug: 'long-sword', chance: 0.25 },
        { itemSlug: 'crossbow-bolt', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'ring-of-dex', chance: 0.25 },
        { itemSlug: 'ring-of-def', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'sewer-rat',
    zone: 'Red Town Sewers',
    name: 'Sewer Rat',
    description: 'A bloated rat the size of a dog, slick with filth and entirely unafraid of you.',
    icon: 'enemy-SewerRat',
    level: 7,
    hp: 60,
    att: 15,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 25,
    goldMin: 2,
    goldMax: 3,
    drops: {
      main: [
        { itemSlug: 'cooked-meat', chance: 0.25, min: 1, max: 2 },
        { itemSlug: 'blue-potion', chance: 0.25 },
        { itemSlug: 'red-potion', chance: 0.25 },
        { itemSlug: 'ring-of-def', chance: 0.25 },
      ],
      always: [{ itemSlug: 'raw-meat', min: 4, max: 8 }],
    },
  },
  {
    slug: 'red-gator',
    zone: 'Red Town Sewers',
    name: 'Red Gator',
    description: 'An enormous rust-coloured gator that has made the storm drains its hunting ground. Slow, armoured in nothing, and very hard to put down.',
    icon: 'enemy-RedGator',
    level: 10,
    hp: 250,
    att: 5,
    def: 0,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 50,
    goldMin: 2,
    goldMax: 3,
    drops: {
      main: [
        { itemSlug: 'red-potion', chance: 0.25, min: 2, max: 4 },
        { itemSlug: 'kite-shield', chance: 0.25 },
        { itemSlug: 'long-bow', chance: 0.25 },
        { itemSlug: 'ring-of-str', chance: 0.25 },
      ],
      always: [{ itemSlug: 'raw-meat', min: 3, max: 5 }],
    },
  },
  {
    slug: 'flying-dung-beetle',
    zone: 'Red Town Sewers',
    name: 'Flying Dung Beetle',
    description: 'An iridescent beetle the size of a shield, droning in lazy circles over the filth. Its shell is worth a small fortune to the right buyer.',
    icon: 'enemy-FlyingDungBeetle',
    level: 8,
    hp: 40,
    att: 20,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: true,
    damageType: 'MELEE',
    xpReward: 50,
    goldMin: 100,
    goldMax: 300,
    drops: {
      main: [
        { itemSlug: 'chakram', chance: 0.25 },
        { itemSlug: 'arrow', chance: 0.25, min: 10, max: 20 },
        { itemSlug: 'ring-of-mag', chance: 0.25 },
        { itemSlug: 'blue-potion', chance: 0.25 },
      ],
      always: [{ itemSlug: 'dirt', min: 1, max: 3 }],
    },
  },
  {
    slug: 'thief-pickpocket',
    zone: "Thieve's Den",
    name: 'Thief Pickpocket',
    description: 'A quick-fingered cutpurse who would rather empty your bag than fight you for it.',
    icon: 'enemy-ThiefPickpocket',
    level: 8,
    hp: 70,
    att: 25,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 30,
    goldMin: 50,
    goldMax: 100,
    drops: {
      main: [
        { itemSlug: 'crossbow', chance: 0.25 },
        { itemSlug: 'crossbow-bolt', chance: 0.25, min: 5, max: 10 },
        { itemSlug: 'arrow', chance: 0.25, min: 10, max: 20 },
        { itemSlug: 'red-potion', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'thief-brute',
    zone: "Thieve's Den",
    name: 'Thief Brute',
    description: 'The muscle of the Den. Twice your width, and he swings something heavy.',
    icon: 'enemy-ThiefBrute',
    level: 11,
    hp: 120,
    att: 30,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 50,
    goldMin: 50,
    goldMax: 100,
    drops: {
      main: [
        { itemSlug: 'giant-club', chance: 0.25 },
        { itemSlug: 'leather-vest', chance: 0.25 },
        { itemSlug: 'crossbow-bolt', chance: 0.25, min: 5, max: 15 },
        { itemSlug: 'blue-potion', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'master-thief',
    zone: "Thieve's Den",
    name: 'Master Thief',
    description: 'The one the rest of them answer to. He watches your hands, not your eyes.',
    icon: 'enemy-MasterThief',
    level: 14,
    hp: 200,
    att: 45,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 80,
    goldMin: 100,
    goldMax: 1000,
    drops: {
      main: [
        { itemSlug: 'crossbow', chance: 0.25 },
        { itemSlug: 'gray-hood', chance: 0.25 },
        { itemSlug: 'warhammer', chance: 0.25 },
        { itemSlug: 'off-hand-dagger', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'skeleton-archer',
    zone: 'The Catacombs',
    name: 'Skeleton Archer',
    description: 'A dry-boned archer that nocks and looses without ever needing to breathe.',
    icon: 'enemy-SkeletonArcher',
    level: 8,
    hp: 50,
    att: 25,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'RANGED',
    xpReward: 30,
    goldMin: 5,
    goldMax: 20,
    drops: {
      main: [
        { itemSlug: 'arrow', chance: 0.25, min: 10, max: 20 },
        { itemSlug: 'short-bow', chance: 0.25 },
        { itemSlug: 'hunter-shield', chance: 0.25 },
        { itemSlug: 'ring-of-dex', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'skeleton-knight',
    zone: 'The Catacombs',
    name: 'Skeleton Knight',
    description: 'Rusted plate hangs off its frame, and it still remembers every guard it was ever taught.',
    icon: 'enemy-SkeletonKnight',
    level: 10,
    hp: 80,
    att: 35,
    def: 15,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 45,
    goldMin: 5,
    goldMax: 20,
    drops: {
      main: [
        { itemSlug: 'gladius', chance: 0.25 },
        { itemSlug: 'kite-shield', chance: 0.25 },
        { itemSlug: 'ring-of-str', chance: 0.25 },
        { itemSlug: 'red-potion', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'skeleton-sorcerer',
    zone: 'The Catacombs',
    name: 'Skeleton Sorcerer',
    description: 'Green light burns in its sockets, and the air goes cold wherever it turns to look.',
    icon: 'enemy-SkeletonSorcerer',
    level: 11,
    hp: 80,
    att: 40,
    def: 5,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MAGIC',
    xpReward: 50,
    goldMin: 5,
    goldMax: 20,
    drops: {
      main: [
        { itemSlug: 'glowing-orb', chance: 0.25 },
        { itemSlug: 'gray-robe', chance: 0.25 },
        { itemSlug: 'wand', chance: 0.25 },
        { itemSlug: 'blue-potion', chance: 0.25 },
      ],
    },
  },
  {
    slug: 'ancient-skeleton',
    zone: 'The Catacombs',
    name: 'Ancient Skeleton',
    description: 'Older than the town above it. The bone has gone hard as stone, and blows glance off it.',
    icon: 'enemy-AncientSkeleton',
    level: 13,
    hp: 120,
    att: 40,
    def: 30,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 80,
    goldMin: 10,
    goldMax: 50,
    drops: {
      main: [
        { itemSlug: 'bone-necklace', chance: 0.25 },
        { itemSlug: 'bone-boots', chance: 0.25 },
        { itemSlug: 'gray-gloves', chance: 0.25 },
        { itemSlug: 'red-potion', chance: 0.25, min: 2, max: 3 },
      ],
    },
  },

  // ==================== THE CATACOMBS — the named dead ====================
  // Omar and Victoria are the fixed bosses of the Sacrificial Chamber (232w) and
  // the Sacred Altar (232v). Legacy stats carried over exactly.
  //
  // Their legacy trait flags have no modern equivalent and are dropped rather
  // than faked: Victoria's eMagImm (magic immunity) and both of their eMag
  // casting flags beyond damageType. Victoria keeps MAGIC damage, so she is
  // defended against with MAG — the recognisable "bring your wits" shape —
  // while Omar hits harder and armours heavier.
  {
    slug: 'omar-the-dead',
    zone: 'The Catacombs',
    name: 'Omar the Dead',
    description: 'He was buried standing up, and has not sat down since. Every blow lands like a dropped headstone.',
    icon: 'enemy-OmartheDead',
    level: 17,
    hp: 250,
    att: 60,
    def: 30,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 150,
    goldMin: 50,
    goldMax: 200,
    drops: {
      main: [
        { itemSlug: 'bone-knuckles', chance: 0.2 },
        { itemSlug: 'bone-cudgel', chance: 0.2 },
        { itemSlug: 'gray-matter', chance: 0.2 },
        { itemSlug: 'red-balm', chance: 0.2 },
      ],
    },
  },
  {
    slug: 'victoria-the-dead',
    zone: 'The Catacombs',
    name: 'Victoria the Dead',
    description: 'She keeps the altar, and speaks the whole time she is killing you. None of it is to you.',
    icon: 'enemy-VictoriatheDead',
    level: 17,
    hp: 250,
    att: 50,
    def: 15,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MAGIC',
    xpReward: 150,
    goldMin: 50,
    goldMax: 200,
    drops: {
      main: [
        { itemSlug: 'victorias-hood', chance: 0.2 },
        { itemSlug: 'bone-boots', chance: 0.2 },
        { itemSlug: 'gray-matter', chance: 0.2 },
        { itemSlug: 'blue-balm', chance: 0.2 },
      ],
    },
  },

  // ==================== BLUE OCEAN — sharks ====================
  // Warrior Pete's "Shark Hunter" targets. Defined here so the quest is complete
  // the moment the Blue Ocean rooms land; nothing spawns them yet, which is the
  // one thing standing between that quest and completion.
  // Legacy eDexImm (dexterity immunity) and ePow (1-in-3 triple hit) have no
  // modern equivalent and are dropped.
  {
    slug: 'hammerhead',
    zone: 'Blue Ocean',
    name: 'Hammerhead',
    description: 'It turns its whole head to look at you, which is somehow worse than the teeth.',
    icon: 'enemy-Hammerhead',
    level: 20,
    hp: 200,
    att: 50,
    def: 50,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    specials: ['power'],
    xpReward: 200,
    goldMin: 50,
    goldMax: 200,
    drops: {
      main: [
        { itemSlug: 'raw-meat', chance: 0.4, min: 2, max: 4 },
        { itemSlug: 'bluefish', chance: 0.3 },
        { itemSlug: 'gray-matter', chance: 0.1 },
      ],
    },
  },
  {
    slug: 'great-white',
    zone: 'Blue Ocean',
    name: 'Great White',
    description: 'The biggest thing in the water that still bothers to hunt.',
    icon: 'enemy-GreatWhite',
    level: 20,
    hp: 250,
    att: 60,
    def: 40,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    specials: ['power'],
    xpReward: 250,
    goldMin: 100,
    goldMax: 300,
    drops: {
      main: [
        { itemSlug: 'raw-meat', chance: 0.4, min: 3, max: 5 },
        { itemSlug: 'bluefish', chance: 0.3 },
        { itemSlug: 'gray-matter', chance: 0.1 },
      ],
    },
  },

  // ==================== DARK FOREST — troll royalty ====================
  // Warrior Pete's "True Troll Champion" and Wizard Morty's "Magic and the Troll
  // Queen". Same note as the sharks: defined now, spawned when the Dark Forest
  // lands. Legacy eRage / eMulti / eStrImm / eDexImm are dropped.
  {
    slug: 'troll-champion',
    zone: 'Dark Forest',
    name: 'Troll Champion',
    description: 'The one the rest of the camp steps aside for. It has no armour and does not appear to need any.',
    icon: 'enemy-TrollChampion',
    level: 35,
    hp: 500,
    att: 100,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 400,
    goldMin: 100,
    goldMax: 500,
    drops: {
      main: [
        { itemSlug: 'troll-gloves', chance: 0.25 },
        { itemSlug: 'troll-boots', chance: 0.25 },
        { itemSlug: 'gray-matter', chance: 0.15 },
        { itemSlug: 'red-balm', chance: 0.2 },
      ],
    },
  },
  {
    slug: 'troll-queen',
    zone: 'Dark Forest',
    name: 'Troll Queen',
    description: 'She does not swing at you. The air does, and it is very cold.',
    icon: 'enemy-TrollQueen',
    level: 40,
    hp: 700,
    att: 140,
    def: 70,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MAGIC',
    xpReward: 700,
    goldMin: 300,
    goldMax: 1000,
    drops: {
      main: [
        { itemSlug: 'gray-matter', chance: 0.3 },
        { itemSlug: 'purple-balm', chance: 0.25 },
        { itemSlug: 'troll-gloves', chance: 0.2 },
      ],
    },
  },
]

function getEnemy(slug) {
  return ENEMIES.find((e) => e.slug === slug) || null
}

module.exports = { ENEMIES, getEnemy }
