// Drop system shape:
//   drops.main      — mutually-exclusive weighted roll: at most ONE item drops per kill.
//                     `chance` values are laid end-to-end; if they sum to < 1.0 the remainder is "no drop".
//                     A winning entry drops qty 1 unless it carries `qty` (fixed) or `min`/`max`
//                     (random qty rolled in [min, max] inclusive).
//   drops.always    — items that drop on EVERY kill (in addition to the main roll). Each entry is
//                     either a slug string (qty 1), { itemSlug, qty } (fixed qty), or
//                     { itemSlug, min, max } (random qty rolled in [min, max] inclusive).
//   drops.firstKill — array of slugs that drop while the player does NOT already own the item.
//                     Typically earned on the first kill, but re-drops on later kills if the
//                     player no longer holds the item (sold/dropped), and stops once owned again.
const STANDARD_MAIN_DROP = [
  { itemSlug: 'redberry', chance: 0.25 },
  { itemSlug: 'blueberry', chance: 0.25 },
  { itemSlug: 'red-potion', chance: 0.25 },
  { itemSlug: 'raw-meat', chance: 0.25 },
]

const ENEMIES = [
  {
    slug: 'rat',
    zone: 'Grassy Field',
    name: 'Rat',
    description: 'A scraggly vermin with yellowed teeth.',
    icon: 'enemy-Rat',
    level: 1,
    hp: 3,
    att: 1,
    def: 1,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 1,
    goldMin: 1,
    goldMax: 3,
    drops: {
      main: [
        { itemSlug: 'string', chance: 0.25 },
        { itemSlug: 'redberry', chance: 0.25, min: 1, max: 2 },
        { itemSlug: 'dagger', chance: 0.25 },
        { itemSlug: 'blueberry', chance: 0.25 },
      ],
      always: [{ itemSlug: 'raw-meat', qty: 1 }],
    },
  },
  {
    slug: 'sand-crab',
    zone: 'Grassy Field',
    name: 'Sand Crab',
    description: 'A large crab with a hardened shell, scuttling sideways across the sand.',
    icon: 'enemy-SandCrab',
    level: 2,
    hp: 3,
    att: 2,
    def: 2,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 2,
    goldMin: 1,
    goldMax: 2,
    drops: { main: STANDARD_MAIN_DROP, firstKill: ['training-helmet'], always: [{ itemSlug: 'raw-meat', qty: 1 }] },
  },
  {
    slug: 'giant-rat',
    zone: 'Grassy Field',
    name: 'Giant Rat',
    description: 'A massive, foul-smelling rodent with red eyes.',
    icon: 'enemy-GiantRat',
    level: 3,
    hp: 6,
    att: 3,
    def: 1,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 3,
    goldMin: 3,
    goldMax: 8,
    drops: {
      main: [
        { itemSlug: 'ring-of-def', chance: 0.25 },
        { itemSlug: 'redberry', chance: 0.25, min: 1, max: 3 },
        { itemSlug: 'blueberry', chance: 0.25, min: 1, max: 2 },
        { itemSlug: 'red-potion', chance: 0.25 },
      ],
      always: [{ itemSlug: 'raw-meat', min: 1, max: 3 }],
    },
  },
  {
    slug: 'gator',
    zone: 'Grassy Field',
    name: 'Gator',
    description: 'A massive reptile lurking in the marsh, coiled and ready to strike.',
    icon: 'enemy-Gator',
    level: 5,
    hp: 100,
    att: 8,
    def: 0,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 20,
    goldMin: 10,
    goldMax: 100,
    drops: {
      main: [
        { itemSlug: 'padded-armor', chance: 0.25 },
        { itemSlug: 'club', chance: 0.25 },
        { itemSlug: 'ring-of-str', chance: 0.25 },
        { itemSlug: 'ring-of-def', chance: 0.25 },
      ],
      firstKill: ['training-armor'],
      always: [{ itemSlug: 'raw-meat', qty: 5 }],
    },
  },
  {
    slug: 'spider',
    zone: 'Spider Cave',
    name: 'Spider',
    description: 'A skittering cave spider with venom-tipped fangs.',
    icon: 'enemy-Spider',
    level: 2,
    hp: 5,
    att: 3,
    def: 1,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 2,
    goldMin: 1,
    goldMax: 5,
    drops: {
      main: [
        { itemSlug: 'raw-meat', chance: 0.25, qty: 2 },
        { itemSlug: 'basic-shield', chance: 0.25 },
        { itemSlug: 'redberry', chance: 0.25, qty: 2 },
        { itemSlug: 'blueberry', chance: 0.25, qty: 2 },
      ],
      always: ['scorpion-tail'],
      firstKill: ['training-gloves'],
    },
  },
  {
    slug: 'scorpion',
    zone: 'Spider Cave',
    name: 'Scorpion',
    description: 'An armored scorpion with a barbed tail poised to strike.',
    icon: 'enemy-Scorpion',
    level: 3,
    hp: 8,
    att: 5,
    def: 2,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 4,
    goldMin: 2,
    goldMax: 10,
    drops: {
      main: [
        { itemSlug: 'dagger', chance: 0.25 },
        { itemSlug: 'blueberry', chance: 0.25, qty: 2 },
        { itemSlug: 'basic-staff', chance: 0.25 },
        { itemSlug: 'basic-hood', chance: 0.25 },
      ],
      always: ['scorpion-tail'],
      firstKill: ['training-boots'],
    },
  },
  {
    slug: 'giant-spider',
    zone: 'Spider Cave',
    name: 'Giant Spider',
    description: 'A massive spider that fills the tunnel with its sprawling legs.',
    icon: 'enemy-GiantSpider',
    level: 4,
    hp: 10,
    att: 6,
    def: 3,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 6,
    goldMin: 5,
    goldMax: 10,
    drops: {
      main: [
        { itemSlug: 'red-boots', chance: 0.25 },
        { itemSlug: 'mace', chance: 0.25 },
        { itemSlug: 'redberry', chance: 0.25, min: 2, max: 6 },
        { itemSlug: 'broad-sword', chance: 0.25 },
      ],
      always: ['scorpion-tail'],
    },
  },
  {
    slug: 'alpha-scorpion',
    zone: 'Spider Cave',
    name: 'Alpha Scorpion',
    description: 'A colossal scorpion, larger and more lethal than any of its kin.',
    icon: 'enemy-AlphaScorpion',
    level: 5,
    hp: 20,
    att: 8,
    def: 5,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 8,
    goldMin: 10,
    goldMax: 20,
    drops: {
      main: [
        { itemSlug: 'basic-hood', chance: 0.25 },
        { itemSlug: 'red-hood', chance: 0.25 },
        { itemSlug: 'green-hood', chance: 0.25 },
        { itemSlug: 'blue-hood', chance: 0.25 },
      ],
      always: [{ itemSlug: 'scorpion-tail', qty: 2 }],
      firstKill: ['long-sword'],
    },
  },
  {
    slug: 'scorpion-guard',
    zone: 'Scorpion Pit',
    name: 'Scorpion Guard',
    description: 'A disciplined scorpion hardened by pit combat, standing watch at the dungeon\'s edge.',
    icon: 'enemy-ScorpionGuard',
    level: 7,
    hp: 30,
    att: 10,
    def: 8,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 10,
    goldMin: 20,
    goldMax: 30,
    drops: {
      main: [
        { itemSlug: 'red-potion', chance: 0.25, min: 2, max: 4 },
        { itemSlug: 'club', chance: 0.25 },
        { itemSlug: 'kite-shield', chance: 0.25 },
        { itemSlug: 'basic-helmet', chance: 0.25 },
      ],
      always: [{ itemSlug: 'scorpion-tail', qty: 3 }],
    },
  },
  {
    slug: 'mammoth-scorpion',
    zone: 'Scorpion Pit',
    name: 'Mammoth Scorpion',
    description: 'An enormous scorpion whose armored bulk fills the tunnel. Its tail strike shakes the walls.',
    icon: 'enemy-MammothScorpion',
    level: 10,
    hp: 70,
    att: 20,
    def: 16,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 25,
    goldMin: 30,
    goldMax: 60,
    drops: {
      main: [
        { itemSlug: 'ring-of-str', chance: 0.25 },
        { itemSlug: 'blue-potion', chance: 0.25, min: 2, max: 4 },
        { itemSlug: 'tower-shield', chance: 0.25 },
        { itemSlug: 'padded-armor', chance: 0.25 },
      ],
      always: [{ itemSlug: 'scorpion-tail', qty: 4 }],
    },
  },
  {
    slug: 'scorpion-queen',
    zone: 'Scorpion Pit',
    name: 'Scorpion Queen',
    description: 'The matriarch of the pit. Her venom dissolves stone and her rage is absolute.',
    icon: 'enemy-ScorpionQueen',
    level: 15,
    hp: 200,
    att: 50,
    def: 40,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 150,
    goldMin: 200,
    goldMax: 500,
    drops: { main: STANDARD_MAIN_DROP, always: [{ itemSlug: 'scorpion-tail', qty: 5 }] },
  },
  {
    slug: 'scorpion-king',
    zone: 'Scorpion Pit',
    name: 'Scorpion King',
    description: 'The apex predator of the dungeon. Ancient, enormous, and merciless — none who have faced him have returned.',
    icon: 'enemy-ScorpionKing',
    level: 30,
    hp: 500,
    att: 100,
    def: 80,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 300,
    goldMin: 500,
    goldMax: 1000,
    drops: { main: STANDARD_MAIN_DROP, always: [{ itemSlug: 'scorpion-tail', qty: 10 }] },
  },
  {
    slug: 'bat',
    zone: 'Bat Cave',
    name: 'Bat',
    description: 'A leathery-winged bat that swoops from the cavern shadows with shrill, piercing cries.',
    icon: 'enemy-Bat',
    level: 2,
    hp: 3,
    att: 2,
    def: 2,
    isAggressive: true,
    isFriendly: false,
    isFlying: true,
    damageType: 'MELEE',
    xpReward: 3,
    goldMin: 5,
    goldMax: 20,
    drops: { main: STANDARD_MAIN_DROP },
  },
  {
    slug: 'golden-bat',
    zone: 'Bat Cave',
    name: 'Golden Bat',
    description: 'A rare bat with shimmering gold-flecked fur. Faster and far more vicious than its lesser kin.',
    icon: 'enemy-GoldenBat',
    level: 6,
    hp: 20,
    att: 8,
    def: 2,
    isAggressive: true,
    isFriendly: false,
    isFlying: true,
    damageType: 'MELEE',
    xpReward: 10,
    goldMin: 100,
    goldMax: 300,
    drops: { main: STANDARD_MAIN_DROP },
  },
  {
    slug: 'salamander',
    zone: 'Bat Cave',
    name: 'Salamander',
    description: 'A thick-bodied cave salamander with damp, mottled skin and a sluggish but punishing bite.',
    icon: 'enemy-Salamander',
    level: 6,
    hp: 30,
    att: 10,
    def: 6,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 9,
    goldMin: 5,
    goldMax: 30,
    drops: { main: STANDARD_MAIN_DROP },
  },
  {
    slug: 'goblin',
    zone: 'Bat Cave',
    name: 'Goblin',
    description: 'A wiry green-skinned goblin clutching a crude blade. Snarls and lunges without warning.',
    icon: 'enemy-Goblin',
    level: 5,
    hp: 20,
    att: 8,
    def: 6,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 7,
    goldMin: 5,
    goldMax: 10,
    drops: { main: STANDARD_MAIN_DROP },
  },
  {
    slug: 'goblin-bandit',
    zone: 'Bat Cave',
    name: 'Goblin Bandit',
    description: 'A scarred goblin wrapped in stolen leathers, wielding a notched short blade with practiced cruelty.',
    icon: 'enemy-GoblinBandit',
    level: 7,
    hp: 40,
    att: 12,
    def: 8,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 12,
    goldMin: 20,
    goldMax: 40,
    drops: { main: STANDARD_MAIN_DROP },
  },
  {
    slug: 'goblin-chief',
    zone: 'Bat Cave',
    name: 'Goblin Chief',
    description: 'The brutal warlord of the goblin tribe. Massive for his kind, draped in bone trophies and roaring for blood.',
    icon: 'enemy-GoblinChief',
    level: 10,
    hp: 120,
    att: 20,
    def: 10,
    isAggressive: true,
    isFriendly: false,
    isFlying: false,
    damageType: 'MELEE',
    xpReward: 30,
    goldMin: 100,
    goldMax: 200,
    drops: { main: STANDARD_MAIN_DROP },
  },
]

function getEnemy(slug) {
  return ENEMIES.find((e) => e.slug === slug) || null
}

module.exports = { ENEMIES, getEnemy }
